### ISSUE TITLE
Support "[[_TOC_]]" tag

### ISSUE THREAD

**Issue by gsemet** [sphinx-contrib/confluencebuilder#1039]
Hello

The `[[_TOC_]]` is often used to generate a table of contents on github/gitlab in single page mode.

Would it be possible to support it, today i have to replace it to `.. confluence_toc::` or automatically remove ?

**Comment by jdknight** [comment]
Unfortunately, this extension cannot provide direct support for such a capability as it does not perform raw syntax processing. This extension relies on sphinx-doc and its extensions to feed it appropriate node information from various parsing actions (e.g. Sphinx-doc processing reStructuredText content (with the help of docutils) and MyST for Markdown). While this extension does include directives such as [`confluence_toc`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/directives/#directive-confluence_toc), it only achieves this by registering the request with Sphinx-docs to process document for such directives.

If using [MyST-Parser](https://myst-parser.readthedocs.io/) for documentation, a suggestion would be to [consult their project](https://github.com/executablebooks/MyST-Parser) for such a request. If MyST-Parser eventually supports the `[[_TOC_]]` format, we can then try to update this extension to support generate a TOC element.

**Comment by jdknight** [comment]
Looked at this again and still feel this is something that the confluencebuilder extension should not explicitly handle (i.e. the Markdown parser should be supporting this, assuming the parser wants to handle `[[_TOC_]]`). However, there is a workaround that can be easily deployed in a project configuration. Consider adding the following into a project's `conf.py` file:

```
import re

def setup(app):
    app.connect('source-read', source_read_handler)

def source_read_handler(app, docname, source):
    source[0] = re.sub('^\[\[_TOC_\]\]', r'```{contents}\n```',
        source[0], flags=re.M)
```

This should replace the `[[_TOC__]]` line with a [reStructuredText's Table of Contents](https://docutils.sourceforge.io/docs/ref/rst/directives.html#table-of-contents). MyST will parse as normal and confluencebuilder should be able to produce a TOC in the final page.

With the presented workaround, going to close this issue. In the future, if MyST (or another markdown extension) does support `[[_TOC__]]` and is not working with the confluencebuilder extension, feel free to re-open or bring up a new issue so that we can improve support for it.
