### ISSUE TITLE
Link to section titles - broken ?

### ISSUE THREAD

**Issue by lutin-malin** [sphinx-contrib/confluencebuilder#1057]
Hi, 

I'm trying to implement a nice pipeline to get documentation to confluence.
Your extension is very much appreciated and doing its job very great.

I'm now struggling to get cross references to work.
Let take this example : 

```rst
Piece2
######


.. confluence_toc::
   :max-level: 3

Sample Header
****************
```
```rst
Piece1
######

:ref:`ref to label section <test_folder/piece2:sample header>`.
```
and with the configuration sample : 

```python
# conf.py
extensions = ['sphinx.ext.intersphinx',
              'sphinxcontrib.confluencebuilder',
              'sphinx.ext.autosectionlabel']
```
on confluence, the generated ref hyperlink is :
`https://<confluence>/display/<space>/Piece2#Piece2-Sample-Header`

while the one working, from the confluence toc :
`https://<confluence>/display/<space>/Piece2#Piece2-SampleHeader`

The target confluence i'm targeting is the Datacenter 8.5.12.

Am i missing anything ? 
I'd really appreciate your help/support on my case.

**Comment by jdknight** [comment]
Hey @lutin-malin,

I tried out the example documentation provided and it does not appear to me that it is valid reStructuredText. For example, this line:

```
:ref:`ref to label section <test_folder/piece2:sample header>`.
```

Results in a warning:

```
.../Piece1.rst:4: WARNING: undefined label: 'test_folder/piece2:sample header' [ref.ref]
```

From what I can tell, you are trying to use the [`sphinx.ext.autosectionlabel`](https://www.sphinx-doc.org/en/master/usage/extensions/autosectionlabel.html) extension to help easily reference a section. It appears that the following content may be what you are looking for:

```
:ref:`ref to label section2 <Sample Header>`.
```

I tested this with both an `html` builder as well as the Confluence builder extension (using a Confluence Data Center v8.9.3 instance) and both appeared to yield expected results.

If I have overlooked anything, please let me know.

**Comment by lutin-malin** [comment]
Thanks @jdknight for looking at my topic.
Your remark is correct, syntax was not correct.

I fixed it according to your indications, but still face the same strange behaviour.
To ease the discussion, i've created a reproduction repository : [reproduction repo](https://github.com/lutin-malin/confluencebuilder-1057)

I'm still experiencing issue on section names that contains spaces. Navigation works to the linked page, but not to the section itself.
The issue is now perhaps related to the extension `sphinx.ext.autosectionlabel`, but i'm not sure.

Let me know if the referenced [reproduction repo](https://github.com/lutin-malin/confluencebuilder-1057) is of any help to expose my topic, and if i can do anything to have the right navigation behaviour.

**Comment by jdknight** [comment]
@lutin-malin, I appreciate the published example. It helps a lot when trying to debug.

There looks to be an issue, especially in anchor generations (or more so, some missing anchor entries). I might have a fix (https://github.com/sphinx-contrib/confluencebuilder/pull/1058) for this, which you can test out (if will) by using the following command:

```
pip install git+https://github.com/sphinx-contrib/confluencebuilder.git@replace-v2-anchor-check-for-named-entries
```

If you can test and verify a correction, this can help the community. No worries if not, since I believe a more proper fix for you would be to configure (or remove) the [`confluence_editor`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_editor) option to `v1`. This is solely since you have indicated that you are using Confluence Data Center. The issue in question looks to be a v2-specific issue. While v2 content may somewhat render on non-Cloud, I believe it is undefined (unless something has changed in more recent Data Center versions). Switching to v1 should use the older anchor references that should automatically work in a Data Center/Server edition.

**Comment by lutin-malin** [comment]
Hi @jdknight 

I think i did not evaluated properly the impact of `v1` and `v2` of the [confluence editor version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_editor).

i'm switching back to `v1`, and works like a charm.


I also tested your branch, and it works as well ! (LGTM :D )

in my opinion, this issue can be closed as well.
Thanks !

**Comment by jdknight** [comment]
Thanks for testing against the branch and glad you are back in a good state.

Will close this issue when we publish the next release.

**Comment by jdknight** [comment]
v2.9 is now available on PyPI -- marking as closed.
