### ISSUE TITLE
Support for math mode

### ISSUE THREAD

**Issue by digulla** [sphinx-contrib/confluencebuilder#136]
The markup page at http://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/markup.html says that math won't be supported.

Using the plugin LaTeX Math, confluence is able to render math formulas. What is preventing your project from rending the necessary markup?

**Comment by jdknight** [comment]
@digulla, I do not believe there is anything preventing support for reStructuredText's `math` directive in this extension. The directive was listed as "unplanned" due to the amount of other changes to be made (autodoc, images, switch to storage format, etc.).

I see that you have mentioned the [LaTeX Math extension](https://marketplace.atlassian.com/apps/1210882) for Confluence. While I would not be against attempting to add support for Confluence Marketplace extensions, since this is not a stock or freely provided addition to Confluence, other changes need to be considered:
- A user should be able to prevent generating macro content on an instance which does not have the macro available. While we do have a restricted macro option (`confluence_adv_restricted_macros`), I would lean towards a change like this to be more of an opt-in solution.
- There appears to be multiple LaTeX math-based extensions. It may be proper to provide a way to allow a user to configure which LaTeX math-based extension to use.
- Extensions are not free. While I do not mind spending a few coinage here-and-there, trying to add support for these extensions and maintain support for these extensions requires a little finesse.

That all being said, it would be nice to be able to support the `math` directive without needing any additional Confluence extension. Doing a quick scan, I see that there is support in Sphinx (1.8+ native; pre-1.8 via `sphinx.ext.imgmath`) to convert math content into images. With upcoming asset support (#135), it may be possible to support the `math` directive for all users. I would not be opposed to include options which allow a user to use a LaTeX-math supported extension instead of having to build/publish images.

So, possible -- just not a trivial change.

**Comment by TxBillbr** [comment]
Noting a similar problem (maybe the same?) I am getting a sphinx warning running 2.0.0 with confluence builder 1.1.0:
`...\sphinx\transforms\post_transforms\compat.py:54: RemovedInSphinx30Warning: Translator for <class 'sphinxcontrib.confluencebuilder.translator.ConfluenceTranslator'> does not support math_block node'. Please update your extension.
  RemovedInSphinx30Warning)

Not sure why as I have no math blocks in my code. I am still not getting anything published to confluence and have no errors. The simple single-page publish seems to work fine, but my 155 pages of hierarchical documentation seems to be failing silently somewhere. I'm running with -vvv. Any suggestions on how to find the problem? 

`

**Comment by jdknight** [comment]
@TxBillbr, the warning should have no effect for you at this time. This warning is currently generated since this extension currently has suppressed math support (i.e. no math support yet, but added implementation so that math logic does not fail when building). Since this extension still supports Sphinx v1.6.3+, it is most likely that message may not go away immediately until math-support is properly investigated.

It is possible that if `sphinx.ext.imgmath` operates as mentioned in a previous comment above and now that this extension supports asset publishing, that this extension would be listed to support the math directive(s) for Sphinx 1.8+. Browsing some comments in Sphinx's world shows that docutils may provide the math-related supported needed (which may or may not be tied to `sphinx.ext.imgmath`). When running on an older version of Sphinx, it would be nice to find a way to ensure any legacy math calls can still exist (to prevent hard failures) without having Sphinx's compatibily logic spamming a warning (or causing other issues).

See also: sphinx-doc/sphinx/issues/5463

----

@TxBillbr, you do mention that you are experiencing publishing issues. If it not the [(now resolved) comment][1] you have mentioned on another issue, I would recommend that you create a new issue about your request (as it would not be related to this math enhancement request). From there, we can discussion possible ways to capture more information about your issue and hopefully find a solution.

[1]: https://github.com/sphinx-contrib/confluencebuilder/issues/117#issuecomment-481389543

**Comment by TxBillbr** [comment]
@jdknight , Thx for the prompt response. I am not one to open an issue until I have done due diligence with my environment and configuration.  I am relatively new to Sphinx, but am experienced with direct publishing to Confluence.  I apologize if my post was perhaps misplaced. If it turns out to be something that should be addressed with an issue, I will create a new one. This is probably better categorized as an enhancement request.

To isolate my Confluence publishing issues, I have tried publishing to an empty space with much better results than publishing to a parent page. I am still working on what the challenge is with publishing to a parent page. I took some time to peruse the source code and have a better understanding of the process and structure. If I had more time/cycles, I would seriously consider forking the project and adding a capability that allows pinpointing the source/code that triggers such warning as well as adding support for ..todo and ..macro directives. I have also considered how one might leverage named anchors on Confluence pages. But alas, that is not for today. As I said in my previous posting, I have no math blocks so it is a puzzle to me what is triggering the warning. As I have so many source files (9K python SLOC + ~70 rst files, locating that is a bit tricky.

**Comment by ncoghlan** [comment]
@TxBillbr Regarding the math_block warning, that actually appears to be a false alarm (sort of) on the Sphinx side: https://github.com/sphinx-doc/sphinx/blob/v2.2.0/sphinx/transforms/post_transforms/compat.py#L29

Because Sphinx changed the way it handles math nodes, v2.2.x emits a warning for all extensions that don't support the new way of handling math blocks. However, it doesn't check if extensions supported the old way before emitting that warning.

**Comment by jdknight** [comment]
See also #262.

**Comment by jdknight** [comment]
With the merge of #262, `master` now includes an initial implementation for math-support in this extension. This includes support for `sphinx.ext.imgmath`-provided capabilities. The general concept for this is that this extension will convert math directives into images, which in turn can get published as attachments to pages.

Note that the system performing the build requires an installation of LaTeX and either dvipng (for png configurations) or dvisvgm (for svg configurations); please refer to the [sphinx.ext.imgmath](https://www.sphinx-doc.org/en/master/usage/extensions/math.html) documentation for more information.

By default, this extension will not adjust the defaults for various configuration entries provided by the `sphinx.ext.imgmath` extension. For those interested, the only recommended change for builders is that the SVG format is ideal:
```
imgmath_image_format = 'svg'
```
This issue will be flagged as completed and will be closed off when the next stable release has been made. Release testing may reveal some possible corrections which, if presented, may be resolved prior to the release. Feel free to comment about issues here prior to the release; however, it is recommended to start a new issue for any specific math-related issues you may be observing.
