### ISSUE TITLE
Support for automodule?

### ISSUE THREAD

**Issue by petebachant** [sphinx-contrib/confluencebuilder#160]
It would be cool if the automodule feature of Sphinx were supported. Currently the docs I build for the main package don't have all functions, and the subpackages have strange formatting. It would also be nice if the source code for the package was converted as well, for linking. I apologize if this is already possible, but I couldn't find it in the docs.

**Comment by jdknight** [comment]
The use of `automodule` (from `sphinx.ext.autodoc`) should have _some_ level of support on `master` (see also [devel-autodocs - automodule](https://jdknight.atlassian.net/wiki/x/AYCTK)). If you are currently using a stable release (v0.9 or earlier), I would not expect any of the autodoc capabilities to work as expected (or at all). Once the next release is made, hopefully some time can be committed to improving this capability. If you are using `master` and see issues (aside from what you have already mentioned in the initial message), the more details on the issue the better. While I will help strive to make autodoc support better with this extension, I personally do not use it in any of the projects I am a part of. I only mention this since I have a lacking set of examples, so I am never confident enough to say everything provided by autodocs will work with this extension. 

Relates to "autosummary: Add support" #145.

**Comment by prasanna-sk** [comment]
Is this the reason why - the individual modules do not appear in the page tree like below? currently, I see navigation to the functions (like below) in the sphinx HTML generated docs - but, not in the Confluence markup.

master
- file1

   - function1
   - function2

- file2

   - function3
   - function4

**Comment by jdknight** [comment]
With the release of v1.2, there should be a significant improvement when attempting to use autodocs/autosummary capabilities with this extension. This includes better formatting for classes, functions, etc. as well as configuring anchors/references to link content between different pages. toctree content also appears to under subsections in a similar fashion to what is observed with using the `html` builder. On this note, this issue will be marked as closed.

That being said, there may be issues for users using autodocs/autosummary capabilities that have not been observed during testing/development. If you still see an issue or something that has been overlooked, please feel free to mention it. Since this issue appears to be more about generic support for auto-based capabilities, it would be recommended to report any new comments/concerns in new issues.

Thanks for bringing up these comments in the first place; they are much appreciated.
