### ISSUE TITLE
toctree not numbered

### ISSUE THREAD

**Issue by jjcaballero** [sphinx-contrib/confluencebuilder#195]
I am trying to publish a pre-existing documentation in Confluence. When I build the docs in latex or html, the generated toctree is numbered. Unfortunately, if I build and publish it using the confluence extension, the toc is not numbered.

I have seen in the docs this statement:
_"Pending work to validate/improve toctree options caption and numbered."_

Does it mean that there are cases where this works?
- If so, so, any clue about what I could change in terms of configuration to make it work?
- If not, is there any plan to work or WIP related to this? Is it doable?

Thanks! BTW, I really like this extension. Good job! 

**Versions:**
- sphinxcontrib-confluencebuilder's extension version: 1.1.0
- Python version: 2.7.3
- sphinx-build: 1.8.5
- sphinx_rtd_theme: 0.1.8

**Comment by jdknight** [comment]
@jjcaballero, unfortunately the `numbered` option for `toctree` has yet to be supported by this extension (mainly since it just has not been gotten around to yet). The markup most likely identified pending work since the options were not explicitly tried and it was unknown if Sphinx/docutils already handled management of numbered entries before this extension did its thing.

On the bright side, such a feature should be doable. From a quick look at things, I can see the following notables to consider if one attempts to support this feature:

- A document's title is extracted/generated from `ConfluenceBuilder._parse_doctree_title` before being registered into a tracking state (in turn, used to help generate things like link titles). This logic needs to be assessed to ensure a title value can be assigned a respective numbered prefixed based on its position and the configuration value of the `toctree` directive. Before attempts are made to just assign a prefix entry to the title, it would be good to confirm that if the numbered prefix values only appear in the rendered toctree elements/title pages or if the prefix also extends to things like internal document links as well.
- A chunk of work would need to be added (around) the `ConfluenceBuilder.process_tree_structure` logic. This extension does various doctree processing to help support document squashing (when in "hierarchy mode"). Implementation needs to be added which the `toctree` element's `numbered` attribute is checked to see if a numbered prefix should be applied to a document (and child documents). Changes need to consider:
  - Applying a prefix on a root document containing a `toctree` which starts a numbering sequence.
  - Ensure the configured depths value works so that if a fixed number value is provided, children beyond that depth will not be numbered.
  - Ensure that no issues arise with the `confluence_max_doc_depth` option set.
- Sphinx's documentation on [toctree][1] indicates that a user should "give the toplevel toctree a numbered option" (under "Section numbering"). This gives the impression that this feature is only really used when the root/master document has been assigned a numerical value. While the documentation indicates this, it would be good to confirm if this is true for documents built with `html`.
- When testing, this feature should be tested against scenarios where `confluence_remove_title` is configured on (default) and off.
- Should include a new set of unit tests to verify this feature.

One could say there is a plan to provide this capability to this extension. Usually any Sphinx documented feature (at least for the `html` builder) aims to be supported by this extension as long as it makes sense for when targeting Confluence. Since you have made this issue, there is a higher chance if it being "scheduled" over other unlisted entries -- but there is no official timeline of when it could be done (days, weeks or months -- whenever free time and will collides). You (and other prospect contributors) are more than welcome in trying to work on this yourself; pull requests are welcome. Either way, I can see this feature being done before the next release. I hope this gives a good idea of the state of things.

(note: this is also somewhat related to #164; although both are different features)

[1]: https://www.sphinx-doc.org/en/2.0/usage/restructuredtext/directives.html#directive-toctree

**Comment by jdknight** [comment]
With changes introduced into #264, the `numbered` option for toctree's should be working on `master` (and available, next stable release; v1.2).

I assume that this issue was primarily focused on the `numbered` option so I will mark it as `pending-next-release` for now and close when the stable release has been made. If I have overlooked another issue, please feel free to mention it.
