### ISSUE TITLE
docname logic broken on Windows

### ISSUE THREAD

**Issue by verdesmarald** [sphinx-contrib/confluencebuilder#200]
The changes from https://github.com/sphinx-contrib/confluencebuilder/pull/172/commits/5a6e5f68529d9c07c89de5be486b2768416f33c1 that were merged in https://github.com/sphinx-contrib/confluencebuilder/pull/172 break link generation on Windows. This is because `builder.env.path2doc` returns a `\`-separated path on Windows, but the following code expects a `/`-separated path.

**Comment by jdknight** [comment]
This appears to be the same issue has discussed in #197. Since this is a newer issue, I will mark it as duplicated; however, the pull request spawned off this issue will most likely be used. I will be marking this issue as closed and future comments on this matter should either be discussed in #197 or #201.
