### ISSUE TITLE
Publishing to Confluence strips out HTML

### ISSUE THREAD

**Issue by mcallaway** [sphinx-contrib/confluencebuilder#213]
When using sphinx confluencebuilder and sphinx confluence, I find that the "built" HTML does include the markup for jira user, but when published to Confluence, that HTML is stripped out of the document.

My extensions are:

    extensions = [
      'sphinx_confluence',
      'sphinxcontrib.confluencebuilder',
      'sphinxcontrib.jinja',
      'sphinxcontrib.plantuml'
    ]

My conf.py has:

    confluence_publish = True
    confluence_disable_autogen_title = True
    confluence_remove_title = False
    confluence_server_url = 'https://mysite.com/'
    confluence_server_user = os.getenv('CONFLUENCE_USERNAME')
    confluence_server_pass = os.getenv('CONFLUENCE_PASSWORD')
    confluence_space_name = 'RD'
    confluence_parent_page = 'Documentation'
    confluence_parent_page_id_check = '52631409'
    confluence_page_hierarchy = True
    if confluence_parent_page is not None:
      confluence_purge = True

Sample source document in .rst has:

```
**Participants**:
····
* :jira_user:`mcallawa`
```

The resulting HTML has the list:

```
  <p><strong>Participants</strong>:</p>
  <ul class="simple">
  <li><p>        <ac:link>
              <ri:user ri:username="mcallawa"/>
          </ac:link>
          </p></li>
  </ul>
```

But the resulting Confluence page is missing the list:

```
Participants:
```

It's missing the `<ul>` entirely.

Why would the act of publishing strip out HTML?

**Comment by jdknight** [comment]
@mcallaway, the extension `sphinx_confluence` provides custom directives (e.g. `jira_user`) which in turn generate respective [`raw`][1] node types based on the `html` output format; however, this extension only permits raw storage format nodes (identified by `confluence`) per design. There is not much this extension can do since it does not know if a raw-provided HTML content is compatible with Confluence storage format (since the generated node could come from other defined directives, document define `raw` types, etc.).

The `sphinx_confluence` extension could be modified to, for example, adjust their generated raw nodes to have both the `html` and `confluence` formats define. So for the [`JiraUserRole`][2], instead of:

```
   attributes = {'format': 'html'}
```
This could be changed to:

```
   attributes = {'format': 'html confluence'}
```
And the extension would work for the raw HTML builder and this extension's provided Confluence builder. But since `sphinx_confluence` is an external extension, I would suggest creating an issue or submit a pull request to [their own project][3] (see also #143).

[1]: http://docutils.sourceforge.net/docs/ref/rst/roles.html#raw
[2]: https://github.com/Arello-Mobile/sphinx-confluence/blob/master/sphinx_confluence/__init__.py#L533
[3]: https://github.com/Arello-Mobile/sphinx-confluence

**Comment by jdknight** [comment]
I assume this inquiry is now resolved and I will mark this issue as closed. Feel free to bring up another comment/issue if something else arises.
