### ISSUE TITLE
Question about refactoring structure of files

### ISSUE THREAD

**Issue by marcinpraczko** [sphinx-contrib/confluencebuilder#222]
Hi, I have generic question related with refactoring strucutre of files.
Lets say that we have following scenario (T0,  T1, T2 - Point in Time)
1. T1 - Initial project - documentation is very simple.
2. T2 - During time project grew and some files have to be moved accross folders in 'docs' strcuture.

My question is not - how confluence builder is managing refactoring of documents in following scenarios.
1. RST file was moved between folders by headline left un-changed (The same headline will be used in confluence)
2. RST Headline changed / File was not moved - So new headline will appear in confluence page.
3. Both changed - RST file was moved and headline has been changed. 

As I do understnad - but I can be wrong. Confluence builder push only new documents unless is forced to purge full structure in confluence. How Confluence builder is handling housekeeping on confluence site? Sphinx allows to run 'make clean' which remove all build folder - then new-fresh documents (and layouts) can be created. How this is working on confluence site?

Thank you in advance for help with this question. I am happy add this to documentation (do PR for this project), so please let me to know how I can understand this correctly.

**Comment by jdknight** [comment]
@marcinpraczko, this extension does not really attempt to deploy a lot of "smarts" when performing the act of publishing a documentation set generated from a Sphinx process (some exceptions with assets to help reduce publish duration/etc.). In the simplest view, it is best to consider that a project will publish documents based off a their detected titles names to anyplace inside [a configured space](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-space-name). But there are many notables and configuration scenarios to consider.

For a documentation set from a Sphinx invoke, there will be an attempt to publish all documents detected with a "proper" title. As new files are added, these pages will be automatically added and published as well. One does not need to purge content in order to recognize new documents.

Typically, this extension does not worry about the placement of a document unless two configurations are in play -- [`confluence_parent_page`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-parent-page) and [`confluence_page_hierarchy`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-page-hierarchy). In a default configuration, pages are normally published in the "root" of a space. If `confluence_parent_page` is configured, documents will be published as a child of that page. Also, if `confluence_page_hierarchy` is configured, pages will attempt to be nested based off of the nested structured defines by Sphinx. Keep in mind that even if a "container" for a publish point is defined for a project, it does not mean that non-Sphinx-specific documents in the same configured space are safe from modification (see [Confluence Spaces and Unique Page Names](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/tips.html#confluence-spaces-and-unique-page-names)].

Changing file names/locations typically do not have an affect unless it adjusts the document's content in some way (via Sphinx includes/etc.) or when hierarchy mode is configured (where placement may be adjusted). Title changes will result in a biggest change since this extension only uses titles to drive publish points into Confluence. This extension makes no attempt to understand the "history" of changes, so if you change the name of a document and re-publish, the older published document will remain untouched (by default). This is the purpose of the [purge feature](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-purge) -- to help lazily cleanup other pages in the space which may not be applicable anymore. The feature is disabled by default since it is a very brute force way of cleaning up a space which may not be desired for various user scenarios.

I hope this information helps.

**Comment by marcinpraczko** [comment]
Hi, thank you for reply. So before closing this issue - last question. As I do know there is option to remove all context before creating new one. How safe is this? For example if I have top document where I am creating all context from sphinx-confluencebuilder, what is a risk that I can loose other context as well? It is realted with my question above - that if I going to refactor structure in sphinx, then before publishing this to confluence, I can delete all context (based on top level document). Question is related with risk of loosing documents outsite of 'scope'?

**Comment by jdknight** [comment]
@marcinpraczko, the [`confluence_purge`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-purge) option is specifically designed to help deal with cleaning up the target context. Instead of pre-clearing a space or container children ahead of time, this extension takes a snapshot of pages before hand, adds/updates pages and then only removes pages that are not part of the new set.

This extension (when `confluence_purge` is configured) will only delete pages that are the ancestor's (via an [CQL](https://developer.atlassian.com/server/confluence/advanced-searching-using-cql/) search) of the configured "container space" ([`confluence_parent_page`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-parent-page)) or all pages of a configured space when [`confluence_purge_from_master`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-purge-from-master) is enabled as well.
