### ISSUE TITLE
Feature: support for OAuth

### ISSUE THREAD

**Issue by forzagreen** [sphinx-contrib/confluencebuilder#234]
In addition to Basic Auth with username/password or username/token, Confluence and Jira support OAuth version 1.

After setting up [OAuth for REST APIs](https://developer.atlassian.com/cloud/jira/platform/jira-rest-api-oauth-authentication/), you get:
- oauth_token
- oauth_token_secret

You can then connect using these tokens.

It's a bit tricky and not documented enough. But here is an example of using OAuth with Confluence:
Pip dependencies: requests_oauthlib
```python
from requests_oauthlib import OAuth1
from oauthlib.oauth1 import SIGNATURE_RSA
import requests

with open("your_private_key.pem") as f:
    RSA_KEY = f.read()

token_auth = OAuth1("CONSUMER_KEY", 
    resource_owner_key="your_oauth_token",  
    resource_owner_secret="your_oauth_token_secret", 
    signature_method=SIGNATURE_RSA, 
    rsa_key=RSA_KEY, 
    signature_type="auth_header")

requests.get('https://your-confluence.com/rest/api/content/123456', auth=token_auth)
```

**Comment by jdknight** [comment]
Planned changes can be seen in #255. Instead of this extension explicitly handling specific authentication handlers (such as OAuth), it allows users to directly pass in custom defined authentication handlers to any generated Requests call.

Feel free to try this out and make additional comments. At this time, it will be assumed what is captured in #255 will be enough to flag this feature request as resolved (unless discussed otherwise); and will in turn be flagged for closure new stable release.
