### ISSUE TITLE
Sub-page links not created due to missing title

### ISSUE THREAD

**Issue by Tanoti** [sphinx-contrib/confluencebuilder#258]
I am trying to build confluence docs for a multi-level set of pages but the build reports a "WARNING: unable to build link to document due to missing title" message and then does not create a link for a child page properly.

Take the following example structure:
```
top.rst
  | foo
  |-- index.rst
    | bar
    |-- index.rst
```
The top-level index ``top.rst`` has a toctree that references ``foo/index``. This sub-index in turn has a toctree that references ``bar/index``. When the docs are built the extension reports "WARNING: unable to build link to document due to missing title (in foo\index): bar/index".

Running in debug mode, I can see the files are mapped using a full (relative) name from the top level but that the sub-level ``bar/index`` does not get a mapping of its own:
```
...
mapping top to title: Top
track top toc-depth: 2
mapping foo/index to title: foo
track foo/index toc-depth: 2
mapping foo/index#foo to target: foo
mapping foo/bar/index to title: bar
mapping foo/bar/index#bar to target: bar
```
Therefore when the ``foo/index`` page is rendered in Confluence Cloud, the link to ``bar`` is just '#'. However, the navigation pane on the left hand side allows access to the sub-pages correctly.

**Comment by jdknight** [comment]
After some investigation, this issue was actually resolved on `master` a few months back (#200). It appears that various issues were accidentally marked as closed before the release has been made. For anyone blocked on this issue, one may opt to use the [bleeding edge sources](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/install.html#master); otherwise wait for a v1.2 stable release (which ideally should be made in the near future (see also #251).

I will marked this as pending-next-release for tracking purposes.

**Comment by Tanoti** [comment]
Many thanks for the reply. Do you have an expected release date for v1.2 so I can plan our upgrade accordingly?

**Comment by jdknight** [comment]
The goal is to have a next release in the first half of January. The most recent updates for the next release will be found in #251.

**Comment by Tanoti** [comment]
@jdknight, many thanks for that, we can wait for the update on that schedule.
