### ISSUE TITLE
Sphinx 2.2.2 warning

### ISSUE THREAD

**Issue by zgoda** [sphinx-contrib/confluencebuilder#265]
```
sphinx/transforms/post_transforms/compat.py:52: RemovedInSphinx30Warning: Translator for <class 'sphinxcontrib.confluencebuilder.translator.ConfluenceTranslator'> does not support math_block node'. Please update your extension.
  warnings.warn("Translator for %s does not support math_block node'. "
```

Additionally, there are warnings that are not thrown with normal HTML Sphinx output:

```
WARNING: unknown code language: shell-session
WARNING: unable to build link to document due to missing title (in index): genindex
WARNING: unable to build link to document due to missing title (in index): py-modindex
WARNING: unable to build link to document due to missing title (in index): search
```

The 1st one is related to pygments lexer but does not appear when building HTML output.

There's also warning on server url, if provided without trailing slash as it is suggested in example in README.

**Comment by jdknight** [comment]
@zgoda, thanks for the feedback; these comments are appreciated.

> does not support math_block node

Unfortunately, there is not a graceful way to prevent the Sphinx engine from disabling this message when a given extension supports both the new math-block implementation and legacy implementation (as this extension still supports running on Sphinx 1.6.3+ at this time).

I wonder if it maybe possible to inject legacy math implementation after the post-transform stage but before documents are translated. I will take a look at this again to see if we can avoid having this warning pushed to users.

> unknown code language: shell-session

Confluence does not provide a shell session-like language for its code macro block (unless this has recently changed), hence why you receive such a warning. This extension will only [map](https://github.com/sphinx-contrib/confluencebuilder/blob/v1.1/sphinxcontrib/confluencebuilder/std/confluence.py#L50) various Pygment names to supported language entries defined by Confluence.

Related to this though, when spot checking what happens for these unknown cases, I do [see it defaulting](https://github.com/sphinx-contrib/confluencebuilder/blob/v1.1/sphinxcontrib/confluencebuilder/translator.py#L507) unknown language types to the Sphinx default type (which in turn, would by Python by default; but also user configurable). I wonder if this is the right approach -- it maybe better just to default unknown languages to a `none` type to prevent applying invalid colors to unknown language types.

> unable to build link to document due to missing title ... [genindex/py-modindex/search]

The documentation set generated from a quick-start will contain references to `genindex`, `py-modindex` and `search` documents assuming a builder will produces these documents. This extension (builder) does not attempt to produce these documents as it relies on Confluence's own search capabilities/etc. for advanced navigation.

The quick-start example was provided to help new users prepare a project using Sphinx's default configuration files and script helpers (`Makefile` and `make.bat`; to help with using more than just this extension's builder). This also had the added benefit of leaving the responsibility of setting up a new project with Sphinx's implementation instead of dealing with this in this extension. I wonder if promoting quick-start is better for new users who want to quickly create a product which initially focuses on using this extension's builder. This project's (currently limited) tutorial documentation could be adjusted to focus on just Confluence-only; and users can make appropriate tweaks to their configurations later to support, let us say, the `html` builder.

> There's also warning on server url, if provided without trailing slash as it is suggested in example in README

An oversight for sure. I will make appropriate corrections to the `README` and other related documentation before next release; thanks for pointing this out.

**Comment by jdknight** [comment]
To follow up on the points provided in this request:

- The warning for `math_block` should have been removed in this extension's v1.2 release.
- While this extension cannot handle language types Confluence does support, the fallback language handling will now be tracked in #282.
- Documentation related to inconsistent server URLs has been corrected.

Since it is believed that all major points have been addressed, will marked this issue as closed; thanks again.
