### ISSUE TITLE
HTML admonitions in Markdown sources not properly typeset

### ISSUE THREAD

**Issue by rechvs** [sphinx-contrib/confluencebuilder#306]
# Used versions
* sphinxcontrib-confluencebuilder: 1.2.0
* Python: 3.7.3
* Sphinx: 2.4.3

# Description
If HTML admonitions are included in Markdown sources, the text within them is
* not displayed at all
This is the case when there are _no_ empty lines separating the HTML code from the actual text.
See the first and second admonition in [index.md](https://github.com/rechvs/sphinx-confluencebuilder-test/blob/master/source/index.md) and the images below.
* displayed without any markup applied
This is the case when there _are_ empty lines separating the HTML code from the actual text.
See the third and fourth admonition in [index.md](https://github.com/rechvs/sphinx-confluencebuilder-test/blob/master/source/index.md) and the images below.

Is this expected? According to [markup](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/markup.html) ReST admonitions are supported, but pure HTML admonitions (or a mixture of HTML and Markdown) are not mentioned.

# Images
Confluence output: ![confluence](https://user-images.githubusercontent.com/35377140/75992441-46be5300-5ef8-11ea-8c1c-081def9923d7.png)
HTML output: 
![html](https://user-images.githubusercontent.com/35377140/75992499-59388c80-5ef8-11ea-8dd2-f0816f41e0eb.png)

## See also

[example project](https://github.com/rechvs/sphinx-confluencebuilder-test)

Keep up the good work!

**Comment by jdknight** [comment]
Unfortunately, this extension has really only focused on support for reStructuredText and Sphinx markup capabilities. While some capabilities may work with this extension and Sphinx processing Markdown-based documents, there is no doubt that there will be limitations. A first look at this, it may be the case where such a capability may not be supported by this extension.

Before diving into dealing with Markdown, first consider how this extension currently builds a Confluence storage-format content (and potentially supporting a future atlas document format) -- this extension will take reStructuredText and Sphinx-defined formatting and ensure the generated storage-format document is compatible with any (supported) Confluence instance. This extension does have some flexibility for advanced users who wish to use the [`raw` directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html#raw-data-pass-through) to manually inject storage-format content -- but typically advanced users would understand the risks/complications of adding such content.

When looking at Markdown (in general), initial concerns would be how [Sphinx deals with the Markdown markup language](https://www.sphinx-doc.org/en/master/usage/markdown.html). From my own very limited knowledge on Markdown formats, it is assumed that most support some level of HTML markup in them. The concern is how do we make sure that the user-provided HTML markup inside documents are storage-format (and possibly atlas document format) compatible? It could be that the Sphinx engine will gracefully serve up HTML blocks to be processed which this extension can sanity check; however, it is unknown how a translator is notified with Markdown content or the best possibly way to sanitize content (hopefully, without introducing new project dependencies if possible).

This issue does show that Sphinx is more than just a reStructuredText parser, so this extension's documentation should be a bit more clear on what capabilities it is supporting in Sphinx. While this extension should be able to provide capabilities with respect to Sphinx + Markdown in the long term, such support would not be a current focus for this development window (at least for myself -- the current priorities are improving auto-based extensions, cleaning up the `singleconfluence` builder and (unfortunately) preparing to support Atlassian's newer Atlas document format). For now, will mark this issue as "investigation" -- users can comment on this issue for more feedback and users are free to submit pull requests related to this (although note the this extension's translator may go through some big changes to support the Atlas document format mentioned above). 

Thanks for reporting this issue.

**Comment by rechvs** [comment]
Thanks for the follow up. For now we’ll work around this issue in the hopes of managing a PR _after_ the big changes.

**Comment by jdknight** [comment]
A follow-up after over a year, this extension should support Markdown through the [MyST-Parser extension](https://myst-parser.readthedocs.io/en/latest/). The leaning towards this extension is primarily though its recommendation on the [Sphinx's Markdown documentation](https://www.sphinx-doc.org/en/master/usage/markdown.html). Additional information on this can be read in #445.

As for `recommonmark`, while this extension does work for the `html` builder, the generated content produces "raw HTML-format" nodes (as mentioned above), which is not something this extension can gracefully re-parse and sanity check. As of v1.5 release of this extension, an advanced option `confluence_adv_permit_raw_html ` exists which will allow raw passing of HTML nodes to a Confluence instance. However, this will most likely not yield expected results for users (e.g. for the example repository mentioned in the original comment, the `warning` class will be forwarded to Confluence; however, Confluence does not support this styling in its theme, so the div block will not be styled).

In addition, since the recommonmark extension is now deprecated by its owners/maintainers, with the promotion to use MyST-Parser instead, there will most likely no intent to support recommonmark's usage in this extension. Therefore, this issue will be closed.

Feel free to try out MyST-Parser (if desired) -- and if any issues arise from using the extension with Confluence builder, please feel free to generate a new issue with the specifics.
