### ISSUE TITLE
Support for labels on pages

### ISSUE THREAD

**Issue by edthamm** [sphinx-contrib/confluencebuilder#313]
As Developer
I want to be able to tag certain pages of my documentation 
so that they can easily be found through filters and overview pages.

I have recently started writing quite a bit of documentation in sphinx and this feature would help me and my colleagues a great deal.

My initial idea is to add a custom directive `.. labels:`

All labels directive occurrences within a page are joined for the final set of labels. Same would happen for the `singleconfluence` builder.

---

I would be willing to implement this myself although I must warn you that I have not created directives before.

I have seen that there is currently an issue with the new style editor and that issue of course takes precedence over such a minor enhancement.

Please let me know what you think.
Cheers

**Comment by jdknight** [comment]
@edthamm, if you want to look at trying to introduced this capability sooner than later, feel free to try to generate a PR. I would be happen to help review/test such a capability.

As you have mentioned, there will be more of a priority to focus on supporting the new document document.

My only major concern would be that such a feature would only be good long term for this extension if managing labels is still supported in the most recent APIs provided by Atlassian (i.e. if Confluence Cloud and Confluence Server 7.x series dropped supported for API-managed document labels, it would not make sense to me to try to support it in this extension).

Other notables to consider would be as follows:
- It may be "better" to use a directive name `confluence_label` instead of just `label` for clarity (and to minimize risk of conflicting with possible other extension directives).
- May want to consider options where a user may want to "stack" labels (add new labels; allow labels from outside publishing) versus "override" labels (removing old/legacy labels); just food-for-thought.

**Comment by edthamm** [comment]
@jdknight cool I'll see when I can find the time. Thanks for offering the assistance.

I will check the APIs for cloud and server. My assumption was that they would keep that because they built their whole aggregation pages feature around that. But you are correct better save than sorry. Will add my results here.

Regarding your other points:

1. I am all in favor on namespaces after all they are a honking great idea and if sphinx wants to support that as a general concept it should be in their main line. You are correct.
1. I have not thought so far yet. Would do this in some testcases for the first review. My first idea was that MVP basically behaves consistent with the `confluence_purge` feature. I.e. labels would only be added unless the page is purged which would remove the page and recreate only currently defined labels. Might not be smart though. I will think on this

**Comment by jaredcurtis** [comment]
Hello,

I've introduced a PR that supports adding labels when publishing a page. This is the first time I've created a Sphinx any advice would be appreciated.

This directive seems a bit odd in that Confluence labels are stored outside of the document therefore the directive doesn't actually introduce any content to page. To work around this I used the builder configuration variable to hold the list of labels and then added them into the JSON blob when publishing via the API. This didn't seem like the best solution to me, does anyone have any other suggestions on how to approach this?

#332

**Comment by jdknight** [comment]
This feature is now available on `master` through the [`confluence_global_labels`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-global-labels) configuration option and the [`confluence_metadata`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/directives.html#confluence-metadata) directive. Thanks for the contributions made to help making this feature available for everyone. This feature should also be made available next stable release.
