### ISSUE TITLE
Multiple sphinx docs projects using same parent page on Confluence?

### ISSUE THREAD

**Issue by danielloader** [sphinx-contrib/confluencebuilder#320]
Is it possible to achieve this or am I going to have to create a blank page to just file the projects under? Given it puts index.rst at the top of the hierarchy and it includes all the information I'd want in a top level page of a project it'd be ideal if multiple projects can publish to the same parent.

So the gist of the request is, can `confluence-purge = True` only pertain to pages matching the same project name?

Thanks

**Comment by jdknight** [comment]
@danielloader, you may be interesting in the [`confluence_purge_from_master`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-purge-from-master) option, which will help target any configured purging based on each project's master document (instead of a specific container).

Although, if you are looking towards a having a single root space/container which can hold multiple flat-styled (non-hierarchical) documents, I can only advise to not enable purging after possibly purging on a first project publication.

If I have misunderstood your request, please feel free to follow up with more information.

**Comment by danielloader** [comment]
That option does sound extremely promising so I'll go experiment and report back.
