### ISSUE TITLE
Support for templates

### ISSUE THREAD

**Issue by zcicala** [sphinx-contrib/confluencebuilder#333]
This may be a more generic Sphinx question.
I am trying to build a bunch of confluence pages from sphinx docs that all have the same layout.
Is there. generic support for templates? I see the header/footer templates for confluence and the kinja support for HTML, but I can't seem to find a generic layout template solution I can use for Confluence

**Comment by jdknight** [comment]
@zcicala, the answer you are looking depends on what you are considering a template/layout for your use case.

What this extension attempts to provide is a translation between reStructuredText/Sphinx markup to markup which is supported by Confluence. How the markup is rendered/styled is typically managed by the [theme](https://confluence.atlassian.com/doc/working-with-themes-151522.html) configured in the Confluence space on the Confluence instance being published to. Dealing with Confluence themes will most likely never be part of this extension's world since installation/configuration of themes are for elevated users in a Confluence instance.

If you are looking for looking for templating content (i.e. not look-and-feel), you may want to investigate using reStructuredText's `include` and `replace` directives (for example, consult [this answer](https://stackoverflow.com/a/9785223/693291) on StackOverflow). You may be able to find more examples online by searching for "reStructuredText templating" -- if you attempt to search for "Sphinx templating", you will most likely only find look-and-feel-related content. That being said, templating content is not really something this extension manages (it mainly deals with parsing/translation and not actual content building).

I hope this information helps.

**Comment by jdknight** [comment]
It is assumed that this issue is focused on the aesthetics of a published documentation set, which is unfortunately outside the realm of what this extension can do (see also #342). Marking as closed.
