### ISSUE TITLE
Edit on Github/Bitbucket link

### ISSUE THREAD

**Issue by sp1thas** [sphinx-contrib/confluencebuilder#339]
Hi,

I recently started to use this Sphinx extension and I totally loved it. Sometimes, there is a confusion among my colleagues regarding the auto-published and the manual-published confluence pages. If the reader is not familiar with the project, will not be sure if a confluence page should be edited using the confluence web UI or directly in the source code.

I think that it would be helpful to implement an "Edit on Github/Bitbucket" functionality. If this functionality is properly configured (provide username/organization, repository name, path), then an extra "Edit on Github/Bitbucket" link should be included at the top of the page.

What do you think?

Although I'm not experienced Sphinx user, I could contribute on this if you agree.

**Comment by jdknight** [comment]
It may be ideal to add a feature will an external "Edit" reference to a document's source. Looks like a common enough feature, especially with the predominate ReadTheDocs theme.

Flagged as an enhancement. You (and anyone else) is free to try to contribute such a feature to this extension -- I would be willing to help review/etc. to get this feature in for others to use. Some recommendations if a feature is planned would be as follows:

- It would be nice to ensure such a feature was generic to what source management is being used (I assume this is considered since both GitHub and BitBucket are being referenced; but just want to ensure other populate tools (like GitLab) or even custom environments with unique source environments (e.g. non-Git) can easily set a reference location).
- It may be good to investigate how [`ConfluenceNavigationNode`](https://github.com/sphinx-contrib/confluencebuilder/blob/v1.2/sphinxcontrib/confluencebuilder/nodes.py#L9) is used in the implementation, since it somewhat relates to the implementation which could be made for this feature.

Note that a current workaround, if desired, would be to take advantage of the [`confluence-header-file`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-header-file) option. A configuration could use this to add a notice/link to indicate that the pages are not really intented to be edited locally ([for example](https://jdknight.atlassian.net/wiki/spaces/confluencebuilder/pages/905838651/v1.2-header+footer+example)).

**Comment by jdknight** [comment]
Support for adding source links (e.g. "Edit on GitHub") has been added in #562; currently on the development branch and should be available next release (v1.7+). Please feel free to try it out by using the bleeding edge sources (if desired; [`confluence_sourcelink`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration/#confval-confluence_sourcelink)) and report any issues you may experience.

**Comment by jdknight** [comment]
v1.7 is now available on PyPI -- marking as closed.
