### ISSUE TITLE
Labels don't seem to work currently

### ISSUE THREAD

**Issue by mschoenlaub** [sphinx-contrib/confluencebuilder#343]
Hi,

trying to set `confluence_global_labels = ['generated']`in my conf.py, but my labels get willingly ignored :)

I came across

https://community.atlassian.com/t5/Answers-Developer-Questions/Creating-a-confluence-page-via-rest-api-with-a-label/qaq-p/469849

which would suggest that the API expects something that is a bit different from what we would do here, no?
E.g. we seem to send a simple string array of labels, while Confluence expects objects with a "name" key.

I could dig into this deeper on the weekend maybe, but right now I am in a bit of a hurry.

**Comment by jdknight** [comment]
@mschoenlaub, thanks for mentioning this.

This issue is this extension's documentation. The [`confluence_global_labels`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-global-labels) configuration is currently only available on `master` (v1.3+). Specifically:

- The configuration entry does not explicitly indicate that it is available on v1.3+, which should be corrected.
- The documentation on ReadTheDocs should be relabelled for clarity, where the existing `latest` should be `master` (HEAD of implementation), `stable` should be `lastest` (for latest stable version) and the new `latest` should be the default documentation.

For now, if you wish to use label support, you may want to use [most recent development implementation](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install.html#master) (if that works for your use case). It should be in a good state, but tested on it has been limited (with respect to testing on every Confluence version). You can also wait for a v1.3 release -- but there is no fixed date (expected between October - December this calendar year).

**Comment by jdknight** [comment]
Changes have been made to the documentation to prevent the promotion of a pre-release feature. The main documentation link on this project's homepage (GitHub) now defaults to the most recent stable release. In addition, the pre-release documentation (`latest`) now includes a warning which may help provide users more information of the state of things.

With this in mind, this issue will now be closed. Sorry for any confusion and hopefully the label assignments will work as expected for you in the next future release. If a specific label issue exists on `master` or v1.3+, feel free to create a new issue outlining the problem.
