### ISSUE TITLE
Broken link at `confluence_ca_cert`

### ISSUE THREAD

**Issue by danieltuzes** [sphinx-contrib/confluencebuilder#353]
No page for [Requests SSL Cert Verification](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification) is found in the [documentation at `confluence_ca_cert`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration.html#confluence-ca-cert)

**Comment by jdknight** [comment]
The Requests documentation appears to be updated to be working now on "python-requests.org". The documentation has also been updated to use the "requests.readthedocs.io" domain (see #359). It is assumed that the latter is "preferred" since it appeared to be the most recent update (and has a "stable" release point).

In any case, I believe this issue has been resolved. Thanks for the report.
