### ISSUE TITLE
Support for requirements extensions like mlx.traceability or sphinx-needs

### ISSUE THREAD

**Issue by skysfalling** [sphinx-contrib/confluencebuilder#376]
Would it be possible to provide support to publish requirements on confluence that are included in the documentation? Currently when I try to build using sphinx-needs, it either doesn't publish that page or throws an error.

**Comment by jdknight** [comment]
@skysfalling, I was able to take a look at both the `mlx.traceability` and `sphinx-needs` extensions today.

First off, I just want to clarify that this extension usually does not attempt to integrate other extension's capabilities inside the implementation. Known exceptions are the Sphinx extensions that exist inside the official Sphinx repository. This extension is always willing to help support the integration of other extensions when possible; however, we avoid directly attempting to include code which could cause long-term maintenance issues.

### [mlx.traceability](https://melexis.github.io/sphinx-traceability-extension/)
It is possible to mostly get this extension to work, although not on the current stable version of this extension (vi PyPI). Using the example documentation found in the MX-Traceability's repository, I was able to get the examples to build and publish to a Confluence instance. This was based off the most recent development revisions which include #399 and #400 (which will be available in the next stable release; v1.3). Example captures are as follows:
 
![image](https://user-images.githubusercontent.com/1834509/101980251-2911dd00-3c32-11eb-82a1-715fa46db34b.png)

![image](https://user-images.githubusercontent.com/1834509/101980280-4fd01380-3c32-11eb-8b7b-6f9ee1b84bd8.png)

Note that its usage will not be a perfect matching. The `mlx.traceability` extension does use some features like Javascript to enhance the experience when using an `html` builder. It is not possible for the `confluencebuilder` builder to attempt to try something like this, since manipulating Javascript is not possible in a stock Confluence instance.

In addition, a quirk is needed if a configuration attempts to use either the `traceability_*_no_captions` configuration options or `:nocaptions:` options in various directives. When a documentation set specifies these, it replaced the caption text to a styled inline value which in the `html` builder environment, will be manipulated to appear when hovering over the caption area. Unfortunately, it is not possible to mimic such a capability. In the event that a no-captions options is used and there is a desire to suppress captions when using the `confluencebuilder` extension, a user can add the following to their configuration:

```
from docutils import nodes

def hook_remove_popup_captions(app, doctree, fromdocname):
    for node in doctree.traverse(nodes.inline):
        classes = node.get('classes', [])
        if 'popup_caption' in classes:
            node.parent.remove(node)

def setup(app):
    app.connect('doctree-resolved', hook_remove_popup_captions)
```

Other than that, there does not appear to be anything major missing here.

### [sphinx-needs](https://sphinxcontrib-needs.readthedocs.io/en/latest/)
Unfortunately, the `sphinx-needs` extension does not appear to gracefully work with the `confluencebuilder` extension. A series of its capabilities appear to rely on a series of styling options and (maybe) Javascript options -- none of these are possible with this extension and a stock Confluence instance. While the content should be able to be published, it may not look nice.

An oddity observed is that the SVG files included do not appear to work in Confluence. While Confluence supports SVGs, for some reason when attached, do not work as expected. I'm not sure if its a content issue in the SVG or Confluence's SVG parser is not handling something properly. If I internally switch the image formats from `svg` to `png` (currently, does not appear to be a public option for a documentation's configuration to set), images do load as expected. However, these images (at least, with the example documentation) appear to be helper images for navigation management (e.g. collapsing content). This then adds to the list of capabilities that cannot really be handled.

There does appear to be several configuration options for the `sphinx-needs` extension. It may be possible to take advantage of them to better handle the mixing of these extensions, but that is just an assumption. At this time, it is most likely the case that the use of the `sphinx-needs` extension will not work with this extension.
