### ISSUE TITLE
Warning on publishing point cannot be found

### ISSUE THREAD

**Issue by astroesteban** [sphinx-contrib/confluencebuilder#413]
I am working on getting our documentation published to our internal Confluence server but I have this issue that when I delete everything under the parent `Docs` page to cleanup the Confluence space and then attempt to publish the docs again:

`WARNING: cannot publish asset since publishing point cannot be found (img.png): user/index`

I can't seem to figure out what is causing this warning but it causes the whole page to fail to even be published. At first I thought it was the relative path causing the problem but even when I move the image to the same directory as _user/index.rst_ I get the same warning.

My environment is:
```
Python 3.7.0

Sphinx 3.3.1
sphinxcontrib-confluencebuilder 1.2.0
```

My docs directory looks like:

```bash
.
├── Makefile
└── source
    ├── assets
    │   └── img.png
    ├── conf.py
    ├── file_one.rst
    ├── index.rst
    ├── internal
    │   └── index.rst
    ├── modules.rst
    └── user
        ├── test.rst
        └── index.rst
```

In my `user/index.rst` I have:

```rst
.. image:: ../assets/img.png
    :align: center
    :width: 600px
    :alt: My image
```

And in the generated `/user/index.conf` file it contains:

```
<ac:image ac:align="center" ac:alt="My image" ac:width="600px">
<ri:attachment ri:filename="img.png"></ri:attachment>
```

**Comment by jdknight** [comment]
@astroesteban, I made an attempt to reproduce this issue and have unfortunately not been able to yet. I will try again tomorrow or later on these upcoming weeks.

Some questions if you have the time:
- If willing, would you mind sharing the version of Confluence data center/server you may be using?
- Does the `user/index.rst` document have a proper heading (assuming it is a self-contained document in the set)? Anything special about its name (casing, special characters, etc.)? Do any other pages having a matching heading?
- Do you see any warnings before that warning message?

Some observations:
- Typically, the error `cannot publish asset since publishing point cannot be found` was only ever observed when a user attempted to provide explicit documents to process in a documentation set, and this extension would attempt to "find" a publishing target if (by chance) it was different from the provided set of documents. I suspect that is not happening here, so it looks like an odd error scenario.
- Since the raw `ac:image` data does not include a page reference inside the macro, it looks like this image is only being used once (which helps narrow down from other possible issues).
- My initial impressions is not that the image/assets content is the issue, but that there is something wrong with publishing the page which should include the image. Asset publishing only occurs after all documents have been published to an instance. It appears from the first time `user/index` may be published (if it ever gets to be published), it somehow disappears before an attachment of the image can be added (hence the missing "publishing point").

**Comment by jdknight** [comment]
This issue originally spawned from a v1.2 release of this extension. Since several corrections/improvements have been made towards image processing (at the time of writing, at v1.8), investigation has not yielded any new results and has been awhile since this issue has been updated; will mark this issued as closed. If this issue can be repeated with v1.8 (or newer) release, please let me know and we can re-open this issue.
