### ISSUE TITLE
Is doctest supported

### ISSUE THREAD

**Issue by aguldbrandsen** [sphinx-contrib/confluencebuilder#460]
platform: Linux-5.3.0-64-generic-x86_64-with-glibc2.29
python: 3.8.5 (default, Feb 2 2021, 15:41:28) [GCC 9.2.1 20191008]
sphinx: 3.5.4
requests: 2.25.1
builder: 1.4.0

I can see in [this documentation](https://sphinxcontrib-confluencebuilder.readthedocs.io/_/downloads/en/stable/pdf/), that doctest should be supported. However, the doctests does not get published to my confluence space, although the rest of the text does. Am i missing some particular configuration? Or is this a bug?

**Comment by jdknight** [comment]
@aguldbrandsen, the use of the [`sphinx.ext.doctest` extension](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html) _should_ be working, although testing/checks on the extension have always been just inspecting if the documented examples (in Sphinx's documentation) render on a Confluence instance. If there is a specific feature or example related to this extension that you can hint at which may have having issues, it can help with determining the root cause.

One known issue with Confluence is its inability to render code-blocks with exactly two characters (see [CONFCLOUD-61941](https://jira.atlassian.com/browse/CONFCLOUD-61941)). If the documentation being used uses a `testoutput` which results in only two characters, the block should still be visible but (undesirably) empty (see also https://github.com/sphinx-contrib/confluencebuilder/issues/198#issuecomment-503370013).

**Comment by aguldbrandsen** [comment]
@jdknight my conf.py in docs contains sphinx.ext.doctest:

```
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.todo",
    "sphinxcontrib.jinja",
]
```


And the code block i am trying to publish:

```
.. doctest::
    >>>import logging
    >>>from mypackage import module
    >>>logger = logging.getLogger("testlogger")
    >>>result = myfunc(logger, "variable")
```

**Comment by jdknight** [comment]
@aguldbrandsen, are you getting output with the `html` builder in this case?

Checking the example provided, it appears that Sphinx will produce no output on any of the builders. The reason that is is due to the directive's implementation supporting arguments; where it expects (at least, from observation) a newline between the directive declaration/options and the contents for the directive. Adding a newline after the `doctest` line should result in rendering on the `html` and `confluence` builders:

```
.. doctest::

    >>>import logging
    >>>from mypackage import module
    >>>logger = logging.getLogger("testlogger")
    >>>result = myfunc(logger, "variable")
```

For example:

_(html builder)_
![image](https://user-images.githubusercontent.com/1834509/115973372-8728c800-a522-11eb-9d5f-78e16bfc5702.png)

_(confluence builder)_
![image](https://user-images.githubusercontent.com/1834509/115973374-8bed7c00-a522-11eb-8f72-eaedf294cbf5.png)

**Comment by aguldbrandsen** [comment]
Hi @jdknight , as a matter of fact, that is how I am doing it already. The newline is there. But the output does, nevertheless, not produce the codeblock in Confluence. I also tried to make the html and inspect them in the browser, but the result here is the same - not codeblocks.

**Comment by jdknight** [comment]
@aguldbrandsen, just for clarity on the following statement:

> I also tried to make the html and inspect them in the browser, but the result here is the same - not codeblocks.

Are you stating that the `html` builder does not produce any code blocks when using a `doctest` directive?

**Comment by jdknight** [comment]
Note, at this time, I have been unable to reproduce an issued state.

Taking the most recent examples from [sphinx.ext.doctest's documentation](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html), the following example code:

```
simple
======

.. contents::
    :local:


section
-------

this is a test


.. testcode::

   1+1         # this will give no output!
   print(2+2)  # this will give output

.. testoutput::

   4

----

.. testsetup:: *

   import parrot

The parrot module is a module about parrots.

Doctest example:

.. doctest::

   >>> parrot.voom(3000)
   This parrot wouldn't voom if you put 3000 volts through it!

Test-Output example:

.. testcode::

   parrot.voom(3000)

This would output:

.. testoutput::

   This parrot wouldn't voom if you put 3000 volts through it!
```

Show the following with an `html` builder:

![image](https://user-images.githubusercontent.com/1834509/141731300-120c3fbb-397a-45f0-97a1-8fb16a3d8edf.png)

And the following when using the Confluence builder:

![image](https://user-images.githubusercontent.com/1834509/141731353-b402454a-f642-4fdc-9d53-4f4572ebe79a.png)

This is showing an expecting match between the two builders.

---

If there is any specific documentation which shows a broken state when using the `confluence` builder that does not work for the `html` builder, please feel free to share it so we can try to correct any possible issue with the Confluence builder extension.

**Comment by jdknight** [comment]
Based on the last comments made and considering the last time feedback was provided, it is believed that either this is no longer an issue or changes made to this extension over time have addressed this. Will be marking this issue has closed. If it is believed that this issue still persists, please feel free to add additional information and we can re-open.
