### ISSUE TITLE
[feature] - Collapsible code block

### ISSUE THREAD

**Issue by andormarkus** [sphinx-contrib/confluencebuilder#491]
Hi All,

Confluence supports collapsible code block through [Code Block Macro](https://support.atlassian.com/confluence-cloud/docs/insert-the-code-block-macro/). 
Sphinx support collapsible code block through ['sphinx_toolbox.collapse'](https://sphinx-toolbox.readthedocs.io/en/stable/extensions/collapse.html) extension.

The sytancs follows:
```rest
.. collapse:: A long code block

    .. code-block:: python

        print("Not really")
```

Thank you for considering this feature

**Comment by jdknight** [comment]
@andormarkus, while there should be a way to achieve this, it will most likely not be included in the Sphinx Confluence Builder extension. This is solely due to the goal on only supporting Sphinx embedded extensions and the extensive testing required each release for all supported Sphinx revisions and Atlassian Confluence Cloud/Server LTS revisions (i.e. to reduce maintenance and testing effort).

That being said, I have been preparing a Sphinx extension on the side to provide "extra" support for the Confluence builder extension. The goal is to support more popular third-party Sphinx extensions out there to work with this extension (e.g. to support out-of-box Sphinx mermaid support with this extension). Ideally this would not add any major burdens on the Sphinx Confluence Builder extension, and still providing an easy way for users to use more extended capabilities. Unknown on any timelines at this time, but it would most likely be done alongside a v1.6 release of this extension.

**Comment by jdknight** [comment]
Well... decided to add support directly in this extension. Hopefully it can make people's life easier and not be too big of an issue to maintain. Support for various sphinx-toolbox nodes have been added in #522; currently on the development branch and should be available next release (v1.7+).

**Comment by andormarkus** [comment]
Wow, thank you so much

**Comment by jdknight** [comment]
v1.7 is now available on PyPI -- marking as closed.

**Comment by senges** [comment]
Hello :wave: 

Sorry to reopen this old issue but I have a suggestion regarding this topic.

First, thanks alot @jdknight ! This is a **great tool**, and thanks to you, with a few tricks, I could manage to move most of my company's documentation to markdown managed with git repos (and there was a lot). It's now fully deployed on confluence using CICD. This is waaay better.

About this, as I wanted to keep the possibility to generate collapsible code blocks (and not code blocks IN a collapsible), I did a little monkey-patch [to the `visit_literal_block()` function](https://github.com/sphinx-contrib/confluencebuilder/blob/d812982162c895b807dc10f35cad7905fc3d99fc/sphinxcontrib/confluencebuilder/storage/translator.py#L653).

```python
classes = node.get('classes', None):
[...]
if 'collapse' in classes:
    self.body.append(self._build_ac_param(node, 'collapse', true))
```

Using `:class:` option is very handy because it won't raise any error as it's [supported by sphinx natively](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-option-code-block-class) and will just be ignored for other generator (html for example).

Not sure if this is out of scope, but I thought it might be helpful to someone trying to tackle this exact same issue in a semi-elegant manner.
