### ISSUE TITLE
plantuml_output_format not respected?

### ISSUE THREAD

**Issue by binaryphile** [sphinx-contrib/confluencebuilder#493]
I'm trying to use confluencebuilder to upload to Confluence Cloud.  I'm using the plantuml integration with the 'svg' output format.  If I render html, it comes out as expected.  If I use confluencebuilder however, it generates png in the output folder.  As a side note, the png links are broken when uploading to cloud (it says they were generated in the legacy editor when I try to edit them).  Since I'd like to use svg anyway, I don't care too much about that, but it would be nice if confluencebuilder would use the svg setting.  Am I doing something wrong?

**Comment by jdknight** [comment]
@binaryphile, you are not doing anything wrong.

Note that the `sphinxcontrib.plantuml` extension implementation provides its own support for preparing image nodes for the Sphinx Confluence Builder extension. The existing implementation only supports generating `png` images (even if `svg` is configured). I have submitted a [pull request](https://github.com/sphinx-contrib/plantuml/pull/61) to correct this.

Second, it appears that Confluence Cloud defaults to a v2 editor which this extension has not yet supported (I assume this may be the same for any newer Confluence Server instances). Until this extension supports ADF (https://github.com/sphinx-contrib/confluencebuilder/issues/347), the legacy editor still needs to be used (due to issues you may have already observed). A pull request (https://github.com/sphinx-contrib/confluencebuilder/pull/494) has been added to the main branch to help correct this. You can install the [most recent development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install.html#development-installation) to correct this (which should be stable enough), or wait for a v1.6 release available in the next month or two.

**Comment by binaryphile** [comment]
Wow, thanks for the quick response (and PRs!).  I appreciate your work.  I'll see if I can get things working.

**Comment by binaryphile** [comment]
I was indeed able to get things working, thank you.  I was a bit surprised at first because the plantuml documentation makes it sound like it just inlines the svg in the html, but I see that it generates separate files for html builder and so it is the same with the confluencebuilder.  I had thought that if it had been inlined I wouldn't need to worry about attachments, but the attachments ended up working out thanks to your modification to confluencebuilder to use the legacy editor.  I did have to archive the existing Confluence pages to get the editor setting to shake loose.  After uploading fresh pages with confluencebuilder, the svgs show up and the editor is the legacy editor.  I'm very happy with the result.

**Comment by jdknight** [comment]
The [sphinxcontrib-plantuml](https://github.com/sphinx-contrib/plantuml) extension has merged in the change mentioned above and is now available in its v0.22 release. In addition, corrections made to address editor/publish issues are included in the most recent stable release (v1.6; now available on PyPI) -- marking as closed.
