### ISSUE TITLE
Command to Bulk remove confluence pages

### ISSUE THREAD

**Issue by KyleBaxter9** [sphinx-contrib/confluencebuilder#503]
Hi,

Just having an issue trying to remove all pages that have been published to a parent_page.
Is there a command which can do this or a way to do this using an API as it needs to be automated and not have me going through each page and creating it.

Thanks

**Comment by jdknight** [comment]
@KyleBaxter9, the development branch has been updated to include the ability to consider the parent page as part of the wipe command available by this extension.

The wipe command with the parent option can be invoked as follows (prospect v1.7+/v2.0+):

    python -m sphinxcontrib.confluencebuilder wipe --parent

Commands are not officially documented yet since they are newer feature of this extension; however, they should be functional and in a good state. Note that the most recent stable release does not have the `--parent` option, so requests will target the removal of all pages for a space. For now, a user can [install the bleeding edge sources](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation) to support the parent option.

**Comment by jdknight** [comment]
v1.7 is now available on PyPI -- marking as closed.
