### ISSUE TITLE
How to replace pages?

### ISSUE THREAD

**Issue by JavierLopezT** [sphinx-contrib/confluencebuilder#595]
Hello. I want to automate the publishing of documentation to my team's space in Confluence. Hence, all the pages should be replaced every time I run the command make confluence.

However, there are other pages (with children) that are manual and I don't want them to be removed/replaced. 

My space looks like this
![Captura de pantalla 2021-12-03 a las 10 39 25](https://user-images.githubusercontent.com/11339132/144580664-e480f22d-9cf5-4aec-b591-bbf8659b2dd7.png)
:

And my index.rst (root doc) is:
```
###########
Airflow
###########
.. toctree::
   :maxdepth: 4
   :caption: Contents:

   local_deployment
   developing_considerations_and_guidelines
   prod_deployment
   maintenance
   templates
   variables
   modules
   changelog
```
So I want the page Airflow (along with its children pages) to be replaced every run of make confluence command. I have tried with the following options in `conf.py`:
```
confluence_purge = True
confluence_purge_from_root = True
```
From my understanding, that would remove only pages under the umbrella of "Airflow". But that is not the case, `make confluence` has tried to remove ALL pages in my space. 

Is there any way to achieve what I want? Thanks

**Comment by jdknight** [comment]
Using `confluence_purge` with `confluence_purge_from_root` should prevent any pages not nested in the root document from being deleted. The configuration provided above looks correct.

> has _tried_ to remove ALL pages in my space

Looking to get a bit more information on this -- when you say "tried", are you observing every other page being removed (which you manually restore later), using the [dry run feature](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confluence-publish-dryrun) that is reporting these other pages as being removed or are only some of the pages being "removed" from other sections?

I ask this since I just want to rule out the scenario where [pages are being moved](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/tips/#confluence-spaces-and-unique-page-names) from other sections into the "Airflow" hierarchy. If, for example, the Airflow documentation has a `maintenance` document with a title `Maintenance`, and if in "Data Science" has a page called "Maintenance", the page will be moved over and replaced. If this is the case, the workarounds to prevent moving (aside from changing the documentation itself) would be to use either [`confluence_publish_prefix`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confluence-publish-prefix), [`confluence_publish_postfix`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confluence-publish-postfix) or [`confluence_title_overrides`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confluence-title-overrides).

If this is not the case (i.e. all other pages are being removed), then there must be something wrong in how this extension detects descendant pages for possible removal. The [check for possible descendants is not that complex](https://github.com/sphinx-contrib/confluencebuilder/blob/43864a5f79018d7c6a9b1a5bff07054ae137e530/sphinxcontrib/confluencebuilder/builder.py#L529-L545). In theory, the first document published should be the documentation's "root" document (`root_doc` or `master_doc`) (since it is the [first document processed](https://github.com/sphinx-contrib/confluencebuilder/blob/43864a5f79018d7c6a9b1a5bff07054ae137e530/sphinxcontrib/confluencebuilder/builder.py#L260-L261) and added to the [publish list](https://github.com/sphinx-contrib/confluencebuilder/blob/43864a5f79018d7c6a9b1a5bff07054ae137e530/sphinxcontrib/confluencebuilder/builder.py#L288)). When publishing documents, the root page should be the first document published, which should [track the root page's identifier](https://github.com/sphinx-contrib/confluencebuilder/blob/43864a5f79018d7c6a9b1a5bff07054ae137e530/sphinxcontrib/confluencebuilder/builder.py#L518-L519); which in turn, should then [be used for the descendants check](https://github.com/sphinx-contrib/confluencebuilder/blob/43864a5f79018d7c6a9b1a5bff07054ae137e530/sphinxcontrib/confluencebuilder/builder.py#L531-L532).

The only thing I can think of at this time is maybe the [status iteration](https://github.com/sphinx-contrib/confluencebuilder/blob/43864a5f79018d7c6a9b1a5bff07054ae137e530/sphinxcontrib/confluencebuilder/builder.py#L692-L695) is not processing documents in order, where if the root document is not first, could result in breaking the descendants check (where all pages would be flagged for possible deletion). If this was the case, it would be nice to know which version of Sphinx is being used. A report statement can generate some useful information, if willing:

    python -m sphinxcontrib.confluencebuilder report

**Comment by JavierLopezT** [comment]
Thanks for your answer. When I first said tried I just saw a logging like "121 pages are being removed" (which are all my pages, not only the ones under the Airflow tree) and then a failure on my API permissions. 

Enabling dryrun feature I have received the next logging:
```
[dryrun] updating existing page Airflow (2331607046)                                                                                                                        
[dryrun] updating existing page Local deployment (2331869204)                                                                                                               
[dryrun] updating existing page Developing consideration and guidelines (2332196866)                                                                                        
[dryrun] updating existing page Production deployment (2332164121)                                                                                                          
[dryrun] updating existing page Maintenance (2331705349)                                                                                                                    
[dryrun] updating existing page Dag templates and examples (2332098573)                                                                                                     
[dryrun] updating existing page Connections, variables and secrets (2332033030)                                                                                             
[dryrun] adding new page Custom code                                                                                                                                        
[dryrun] updating existing page pf_utils package (2332000262)                                                                                                               
[dryrun] updating existing page plugins package (2331705364)                                                                                                                
[dryrun] updating existing page Changelog (2331607078)                                                                                                                      

removing legacy pages... (total: 121) [dryrun] removing page Trends (2207481874)                                      
[dryrun] removing page April 2019 -> April 2020 (1008926721)       
more removing statements
done
```             
The curious part is, these "legacy" pages have not been actually removed. They are still visible in my confluence space exactly as they were. So I don't understand why is this happening. Any idea?

The report command output is here:
```
(system)
 platform: Linux-5.10.47-linuxkit-x86_64-with-glibc2.28
   python: 3.9.6 (default, Jun 29 2021, 19:27:32) [GCC 8.3.0]
   sphinx: 4.3.1
 requests: 2.25.1
  builder: 1.5.0

(configuration)
confluence_page_hierarchy: True
confluence_publish: True
confluence_publish_dryrun: True
confluence_purge: True
confluence_server_pass: (set)
confluence_server_url: https://<removed> (cloud)
confluence_server_user: (set)
confluence_space_name: (set; upper)
```

Also, the purge word made me afraid of permanently deleting some pages. According to the English Confluence documentation, it seems that removing is when you move a page from the space to the archive, and purging is when you remove permanently that page from the archive. I inspected the code of this package in Github and I saw that purge options are actually removing and not purging, but still, I am not confident at 100%. 

Thanks!

**Comment by jdknight** [comment]
> ```
> removing legacy pages... (total: 121)
> [dryrun] removing page ...
> ...
> ```
> 
> The curious part is, these "legacy" pages have not been actually removed. They are still visible in my confluence space exactly as they were (under Data Science, Data Engineer and in the root of the space). So I don't understand why is this happening. Any idea?

If the ask is why these pages are not being removed here when the output states so, this is a result of the dry-run action (where it will not actually add/edit/remove content -- but it will run queries on the Confluence instance to see what would happen).

> 
> The report command output is here:
> ...
> (configuration)
> confluence_page_hierarchy: True
> confluence_publish: True
> confluence_publish_dryrun: True
> confluence_purge: True
> confluence_server_pass: (set)
> confluence_server_url: https://<removed> (cloud)
> confluence_server_user: (set)
> confluence_space_name: (set; upper)

The output of the report command does not have `confluence_purge_from_root` listed. Are you sure it is configured in the documentation's `conf.py` file? The report command should output all detected/used configuration options found in the documentation's configuration -- unless we have an issue with the report command.

> Also, the purge word made me afraid of permanently deleting some pages. According to the English Confluence documentation, it seems that removing is when you move a page from the space to the archive, and purging is when you remove permanently that page from the archive. Before you confirmed in your answer that pages deleted by this package can be restored, I had to inspect the code in Github and I saw that purge options are actually removing and not purging, but I was still not 100% confident that I was not going to mess up my space.

You are correct about what this extension's meaning of "purge" means. Pages that are flagged as old are only "removed" (queued into the trash); this extension does not perform an administrative purge for a space. Any page that does get removed by this extension _should_ be recoverable by a site's administrator (via a restore page option).

**Comment by JavierLopezT** [comment]
Thanks for your help. I was using version 1.5, that's why the report didn't catch `confluence_purge_from_root`. When I upgraded the library, all worked as expected. Thank you very much again and sorry for wasting your time

**Comment by jdknight** [comment]
@JavierLopezT, no worries. I'm glad you got it working.
