### ISSUE TITLE
What are the permissions needed to use this package with confluence server?

### ISSUE THREAD

**Issue by FeryET** [sphinx-contrib/confluencebuilder#599]
Hi.

I'm trying to create a documentation page, but upon running `make confluence` I get this error:

```
---
Permission denied on Confluence (REST GET)

The configured user does not have permission to perform an action on the
Confluence instance.
```

I can't find any logging options to check in detail what is exactly happing. I have the permissions to create pages in the page I've put in `conf.py`, but apparently confluencebuilder can't do that. Any ideas how to debug this? I'm suspecting maybe this package needs more than just a user-access for documentations.

**Comment by jdknight** [comment]
A permission denied error occurs when the access point returns a 403 error. This could either be the Confluence instance reporting the user does not have permission or a client is not properly authenticated with a (reverse) proxy.

Typically, a user would want Confluence permissions for a specific space to have "Add" permission for pages/attachments; and possibly "Delete" permissions, if supporting content purging. These are typically enabled in default setups, but it depends on how a Confluence administrator configures a given space.

Speculating here, but since the error message indicates "Permission denied on Confluence (REST GET)", it looks to be a first-read (GET) request, attempting to query the instance. If you are using the same user which you can also navigate/create/edit pages with using a browser, this may be an authentication issue with the environment invoking the Sphinx publication request. For example, if you have a server URL configured as follows:

```
confluence_server_url = 'https://intranet-wiki.example.com/'
```

And in a browser you can navigate to:

```
https://intranet-wiki.example.com/confluence/rest/api/search
```

And see a response such as the following:

```
{"statusCode":400,"data":{"authorized":false,"valid":true,"errors":[],"successful":false},"message":"com.atlassian.confluence.api.service.exceptions.BadRequestException: cql query parameter is required"}
```

The URL is fine. And if you try the same REST call on your shell (using `curl` or `wget`):

```
curl https://intranet-wiki.example.com/confluence/rest/api/search
```

And see a different result, you may require additional options (such as [`confluence_server_auth`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_server_auth) or [`confluence_server_cookies`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_server_cookies)).

---

One approach could be to enable all Requests logging inside a Sphinx configuration (`conf.py`) using something like the following:

```
import logging
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
rlog = logging.getLogger('requests.packages.urllib3')
rlog.setLevel(logging.DEBUG)
```

And as you run the publishing stage, each request should be dumped to the standard output stream. For example:

```
...
generating index... done
generating index (py-modindex)... done
generating search... done
DEBUG:urllib3.connectionpool:https://example.atlassian.net:443 "GET /wiki/rest/api/content?type=page&spaceKey=TEST&title=index&status=current&expand=version%2Cmetadata.labels HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://example.atlassian.net:443 "PUT /wiki/rest/api/content/123456789?status=current HTTP/1.1" 200 None
...
```

If it fails at a later point, it could point to an issue with a specific page/request being made. If it happens on the first request, it is most like a setup/authentication issue as mentioned above.

**Comment by root42** [comment]
I have the same problem:
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): confluence.foo.bar:443
DEBUG:urllib3.connectionpool:https://confluence.foo.bar:443 "GET /rest/api/space?limit=1&spaceKey=C2330 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://confluence.foo.bar:443 "GET /rest/api/search?limit=2&cql=type%3Dspace+and+space.title~%22C2330%22 HTTP/1.1" 403 None
```

However I  wonder what that second request is...? The first one seems to try and get the correct Confluence Space (C2330). The second...?

**Comment by jdknight** [comment]
> I have the same problem:
> 
> ```
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): confluence.foo.bar:443
> DEBUG:urllib3.connectionpool:https://confluence.foo.bar:443 "GET /rest/api/space?limit=1&spaceKey=C2330 HTTP/1.1" 200 None
> DEBUG:urllib3.connectionpool:https://confluence.foo.bar:443 "GET /rest/api/search?limit=2&cql=type%3Dspace+and+space.title~%22C2330%22 HTTP/1.1" 403 None
> ```
> 
> However I wonder what that second request is...? The first one seems to try and get the correct Confluence Space (C2330). The second...?

The [second `GET` request](https://github.com/sphinx-contrib/confluencebuilder/blob/e3f227e69bd83551546048a5212c0d50d4dc2e5c/sphinxcontrib/confluencebuilder/publisher.py#L70-L81) is invoked in a situation where the original space key cannot be found. The intent of this feature was to help find/report a space with a similar name, since it has been reported a couple of times where users would use a difference space key casing/etc. and wonder why it couldn't find their space.

In this case, while an success (200) REST call was performed on the Confluence instance, the successful response here is most likely that the Confluence reported that "hey, the request is fine, but I have no space with that name". This is either that the space key does not exist (which I assume is not the case) or that the user requesting a search does not have permission to know that such a space key exists. I recall seeing in the past that anonymous/"unauthorized" requests would have a 200-reported search call with zero results, but a more explicit search can result in a hard authentication failure (403).

In all cases I have seen, a `403` reported error code is solely a result of an authentication issue -- either with the credentials being used to authenticate, or a result of a additional access layer added for Confluence non-Cloud in some corporate environments.

**Comment by root42** [comment]
@jdknight thanks for the response! I raised an issue with out IT department, and they changed something -- and suddenly it works again. :) Sadly I don't know what they changed, but afterwards confluencebuilder was able to upload again. Great piece of software!

**Comment by jdknight** [comment]
It is assumed based of the feedback and duration since these events have occurred, these issues have either be resolved or are no longer issue. With that in mind, marking these issues as closed. If this is incorrect, please mention so and we can re-open this issue.
