### ISSUE TITLE
Feature request: control page width

### ISSUE THREAD

**Issue by michcio1234** [sphinx-contrib/confluencebuilder#602]
I would like to be able to set published page width, so that the content does not take up 100% of available width.

This is what a Confuence page looks like in full width:

![image](https://user-images.githubusercontent.com/16254622/151207033-56899eec-7bf8-49de-8c2d-586023a45801.png)

And this is what it looks like in a narrow version (long text is much easier to read this way IMO): 

![image](https://user-images.githubusercontent.com/16254622/151207184-00cd3841-9f6b-459e-9918-f31346575b23.png)

In **new** Confluence editor (Confluence Cloud, build 1000.0.0-c37d92d1121c) the width is controlled with this little arrow in upper-right editor corner: 
![image](https://user-images.githubusercontent.com/16254622/151348284-8f421650-1809-4f55-8db5-38d041096243.png)

It looks like the Confluencebuilder is using an old format, though (Confluence opens an old editor if I try to edit a generated page). In old editor, what I want to do can be achieved by selecting single column layout:
![image](https://user-images.githubusercontent.com/16254622/151347532-0cb80b05-a3f5-47b6-b738-32ab1812e17f.png)

Would it be possible to add a configuration variable that would make published pages narrow?

If you could at least point me where to start, maybe I could add this feature. But unfortunately I know nothing about Confluence format nor Sphinx internals. :/

By the way, thank you for the great product. It makes my work much easier. :)

**Comment by jdknight** [comment]
This is unfortunately unavailable at this time. This is tied to #347, which aims to support Confluence's newer editor.

Pages have a content property options -- specifically, a `content-appearance-published` which looks to be either configurable to `full-width` or `default`. With the newer editor, `default` appears to be the new (smaller) width size and `full-width` being the full width of the page. While it looks like content pages using the older editor can set either of these values, the `default` configuration for these editors appears to match the `full-width` as well. There may be an undocumented option to force a "smaller" width on a page; however, I would assume the appearance option only applies to the newer editor.

For now, such a feature would have to wait until #347 is completed. See also [this comment](https://github.com/sphinx-contrib/confluencebuilder/issues/600#issuecomment-1007736608) for more information on the recent state of things.

**Comment by michcio1234** [comment]
I experimented a bit. 

I open the page published with Confluencebuilder. I went to ... -> Advanced details -> View storage format.

Then I edited the page manually in the (old) Confluence editor to be Single-column (which appears as nice narrow column - just what I want). I saved it and checked the storage format again.

The difference is that after the edit, the source got surrounded with:
```
<ac:layout><ac:layout-section ac:type="fixed-width"><ac:layout-cell>
...
</ac:layout-cell></ac:layout-section></ac:layout>
```

Is this something that can be added to the (old) builder? 

If you could point me to a place where this should be added, I should be able to test it on my own.

**Comment by jdknight** [comment]
If you wish to just apply those tags are the start/end of all pages, you could (at this time) take advantage of the [`confluence_header_file`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_header_file) and [`confluence_footer_file`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_footer_file) options. These files accept raw content which you can inject these storage format tags.

I assume the main different between using the layout option and the restricted-width-new-editor option is that the layout option only applied to content (where the other include navigational content as well). If you are looking to propose this as a fixed feature (assuming the layout stuff work as expected), I would not object to it. Having the ability to pick between the page width for the upcoming ADF builder will be an available configuration option for users to take advantage of. Not sure off hand would be a good name (something like `confluence_layout_width`?).

If interested, the code you would want to be would be somewhere in [`sphinxcontrib/confluencebuilder/storage/translator.py`](https://github.com/sphinx-contrib/confluencebuilder/blob/master/sphinxcontrib/confluencebuilder/storage/translator.py). In theory, you would want to introduce `visit_document`/`depart_document` and ensure [the parent methods](https://github.com/sphinx-contrib/confluencebuilder/blob/cd6c0991d92407bd15731898ea1cc58c410959e3/sphinxcontrib/confluencebuilder/translator.py#L81-L84) are invoked. The only other consideration I can think of is possible handling a situation where the `singleconfluence` builder is invoked -- since a document tag is processed per page, so this may stack multiple blocks of layout sections (but that could be fine in the final rendering).

**Comment by michcio1234** [comment]
Yess, header/footer did the trick! Thank you!

**Comment by jdknight** [comment]
There is now a new issue (see #642) tracking all the notables to consider when supporting the EditorV2 capabilities. The ability to control the page's width has been noted in this issue and is planned to be supported when this feature becomes available. With that in mind, this issue will be marked as closed. Users interested in tracking the features outlined in this issue should now refer to #642 instead.
