### ISSUE TITLE
math support

### ISSUE THREAD

**Issue by danieltuzes** [sphinx-contrib/confluencebuilder#614]
How is math supported? I didn't find a link on your feature page https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/features/

Our org has https://docs.adaptavist.com/cfm4cc/latest/macros/latex
is it enough to push formulas to our confluence server?

**Comment by jdknight** [comment]
Math is supported using the [`math`](https://docutils.sourceforge.io/docs/ref/rst/directives.html#math) directive when using the [sphinx.ext.imgmath](https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.imgmath) extension (which the math extension also requires a LaTeX and [dvipng](https://savannah.nongnu.org/projects/dvipng/) or [dvisvgm](https://dvisvgm.de/) installation; outlined in its documentation -- this is usually covered by a TeX suite installation on a Linux system or a MiKTeX installation on a Windows system). An example of this can be seen on the [Math demonstration page](https://sphinxcontrib-confluencebuilder.atlassian.net/wiki/spaces/STABLE/pages/7340252/Math) ([additional recommendations](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/tips/#recommended-options-for-math) can be found in the Tips documentation).

If you wish to take advantage of Adaptavist's LaTeX macro, you could try injecting a raw macro of the content you wish to render. An example could be something like the following: 

```
.. raw:: confluence_storage

    <ac:structured-macro ac:name="latex-formatting" ac:schema-version="1">
        <ac:plain-text-body><![CDATA[$ax^2 + bx + c = 0$]]></ac:plain-text-body>
    </ac:structured-macro>
```

Although, you will have to check if the macro name is correct by inspecting an example output on a test page (i.e. manually creating a page with a LaTeX math example, selecting  "Advanced -> View storage format" of the page and copy/pasting/edit the example into the raw directive block).

**Comment by danieltuzes** [comment]
Thanks for the prompt reply. Using static images is not really a solution in 2022, and if my system and server both support latex, why cannot the confluence builder support it?

By using the suggested workaround, how can I keep the original functionality of the rst, and make HTML if it is needed? It seems it breaks usability, and the rst will suit only the confluence build. Isn't it possible to define a new role, that is interpreted as math, if the builder is not confluencebuilder, but interpreted as per your suggestion, if the builder is confluencebuilder?

**Comment by jdknight** [comment]
> [If] my system and server both support latex, why cannot the confluence builder support it?

The Confluence builder extension aims to provide as much functionality it can with respect to supporting the features provided by Sphinx on a Confluence instance's stock capabilities. Adaptavist's LaTeX macro is a paid extension solution, which fits outside the scope of what the Confluence builder extension tries to support.

That being said, Confluence builder extension tries to be flexible enough to allow a user to handle things like custom macros (either internally build or third-party solutions). Using the [`raw` directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html#raw-data-pass-through) is just one of the means where a user has the freedom to utilize any type of custom markup they wish to apply.

I can agree that it is annoying -- to want to just be able to use an example markup like the following:

```
.. math::
 
    E = mc^2
```

And have it "just work" on all builder types without complication. While it would be nice to use the [sphinx.ext.mathjax](https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.mathjax) capabilities which are used in the `html` builder, there is not a way to push script on a stock Confluence instance to handle this. This is why this extension defaults/forces the use of using the [sphinx.ext.imgmath](https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.imgmath) extension since (1) it is a capability provided by Sphinx and (2) Confluence easily supports image content on pages. While SVG generated images can look fine for a user (assuming no browser issues), there is the annoyance of not having capabilities to raw copy text and other manipulations which may be provided by a mathjax solution.

> [How] can I keep the original functionality of the rst, and make HTML if it is needed?

There are ways you could make this work in your environment. While you could use both a combination of `raw` directives targeting Confluence and "not Confluence" format, I think we can all agree that is not an ideal solution. We would want to way where one could just define a `math` block and have it work on all the builders we use.

Typically, a solution like this could be achieved by just overriding the node types in a project's `setup` call to override how math nodes are processed (see [this comment](https://github.com/sphinx-contrib/confluencebuilder/issues/598#issuecomment-988381979) an example). However, with the existing implementation of the Confluence builder extension, there isn't a way to stop it pre-converting math nodes into image nodes before node translation processing kicks in.

A workaround would be adding the following into your documentation, where we replace math nodes to a custom LaTeX node, and then wrap the contents with an assumed-valid `latex-formatting` macro. Is it not pretty, but in a project's `setup.py`, you could add the following:

```
from docutils import nodes
from sphinxcontrib.confluencebuilder.builder import ConfluenceBuilder
from confluence_support import MathOverride
from confluence_support import override_math_mode


def custom_visit_latex_math(self, node):
    self.body.append('<ac:structured-macro ac:name="latex-formatting" ac:schema-version="1">')
    self.body.append('<ac:plain-text-body><![CDATA[')


def custom_depart_latex_math(self, node):
    self.body.append(']]></ac:plain-text-body>')
    self.body.append('</ac:structured-macro>')


def confluence_builder_inited(app):
    if not isinstance(app.builder, ConfluenceBuilder):
        return

    app.add_transform(MathOverride)


def setup(app):
    app.add_node(override_math_mode,
        confluence=(custom_visit_latex_math, custom_depart_latex_math),
        override=True)

    app.connect('builder-inited', confluence_builder_inited)
```

And create a `confluence_support/__init__.py` file alongside your documentation which defines:
```
from docutils import nodes
from sphinx.transforms import SphinxTransform
from sphinx.util.math import wrap_displaymath
import itertools

class MathOverride(SphinxTransform):
    default_priority = 99

    def apply(self, **kwargs):
        for node in itertools.chain(self.document.traverse(nodes.math),
                self.document.traverse(nodes.math_block)):

            if not isinstance(node, nodes.math):
                if node['nowrap']:
                    latex = node.astext()
                else:
                    latex = wrap_displaymath(node.astext(), None, False)
            else:
                latex = '$' + node.astext() + '$'

            new_node = override_math_mode(latex, latex, **node.attributes)
            node.replace_self(new_node)


class override_math_mode(nodes.TextElement):
    pass
```

_(we have to create a different file primarily to hold the node definition, or Sphinx can fail when attempting to pickle/cache the node type)_

While adding the above is not fun, it should be when using a combination of builders like `html` and `confluence` (although, limited testing has been done).

In the future, we can change the Confluence builder extension to possibly detect for custom overrides provided by the Sphinx configuration on the math type, and then prevent it from auto translating math blocks into image blocks. This would avoid the need to add this custom node type/transform into a configuration -- allow users to more simply override these node types or enable extensions stacked on top of the Confluence builder extension to manipulate content as they see fit.

**Comment by danieltuzes** [comment]
Thanks, will try it out!

**Comment by jdknight** [comment]
Another idea is that we could add an advanced option in this extension, which when set, will just forward Math-defined LaTeX to a custom-defined macro for a user. That will allow this extension to properly extract/parse the LaTeX content and leave it up to the user to say what macro will process it ~ then users would be free to inject this content into any type of macro definition which could support LaTeX processing (although I wonder what would be the best way to properly test this in terms of development...).

**Comment by danieltuzes** [comment]
I am not familiar what a macro means in the rst world, but I am not against installing katex or mathjax into my sphinx environment to get the right HTML or confluence output. I just don't want to maintain 2 versions of my rst files, one for HTML output and one for confluence, yet I want proper math rendering. And within a decade, I'll also want proper equation numbering and references :)

**Comment by jdknight** [comment]
Sorry, for clarification (and if interested), when I talk about macros, I am talking about the features supported by a Confluence instance. Confluence provides a series of "standard" macros, such as the "info" blocks or "code" blocks. These are typically enabled/supported on all Confluence instances, which the Confluence Builder extension for Sphinx will attempt to utilize.

The LaTeX macro you mentioned in your environment is provided by Adaptavist, and is limited to the instances which have purchased/installed the [Content Formatting Macros](https://marketplace.atlassian.com/apps/247/) application. The Confluence Builder extension for Sphinx focuses on the stock/default-provided macros -- since we do not want to convert a reStructuredText `math` directive into a Adaptavist LaTeX macro and have users who do not have this macro seeing a broken math block. For example:

![image](https://user-images.githubusercontent.com/1834509/154379939-cd3e9199-8fa0-44c3-88e4-b612335d5760.png)

This is why the existing implementation of this extension relies on 
[sphinx.ext.imgmath](https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.imgmath) -- since Sphinx provides the extension and all Confluence instances default-support image macros.

My recent suggestion above was a possible approach to give flexibility for users who want to use an alternative LaTeX rendering for their math definitions. There looks to be several implementations of LaTeX macros available on the Confluence marketplace. So -- trying to think of a possible way (aside from just having users rely on the `raw` directive) to easily translate a `math` block into using a LaTeX rendering of their choice -- and avoiding generating/attaching images (without even getting into Math capabilities which may be supported by a Markdown format). An idea is that we could default to use `sphinx.ext.imgmath` for math blocks, but provide a way (for example) a user to define `confluence_advanced_math_macro = '<ID>'`. If this is set, we can have this extension automatically parse the math content into LaTeX (as Sphinx does with any other builder), and forward it to the macro type support on a users Confluence instance.

**Comment by jdknight** [comment]
@danieltuzes, I took some time to try to help improve support for users wanting to integrate with LaTeX macros. Using the [most recent development implementation](https://sphinxcontrib-confluencebuilder.readthedocs.io/install/#development-installation), changes (#620) have been made to support a new configuration option [`confluence_latex_macro`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration/#confval-confluence_latex_macro). If set, math (and other LaTeX content) can be rendered on Confluence using a LaTeX macro installed on an instance (if any).

Recently added a new [math guide](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/guide-math/) to the documentation. Please take a look, and if there is anything unclear from it, we can try to improve this information before we make a next release.

One final note, which I was not aware was the case with the current release, but SVG images for math will not be rendered unless [sphinx.ext.imgmath](https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.imgmath) was explicitly listed in the extension's configuration. Previous to v1.7, we force-loaded this extension to ensure easy SVG support; however, this would cause issues where if the Confluence builder extension was listed, other builders would be forced to use this extension as well. When correcting this in v1.7, the new requirement was not explicitly mentioned anywhere what had to be done. This information should now be reflected in the same guide referenced above.

**Comment by jdknight** [comment]
v1.8 is now available on PyPI -- marking as closed.

**Comment by danieltuzes** [comment]
Thanks, this will make this plugin more useful for companies paying for Confluence and macros.
