### ISSUE TITLE
Plantuml generated svg files can't be found

### ISSUE THREAD

**Issue by skyscribe** [sphinx-contrib/confluencebuilder#641]
I'm using this extension in together with plantuml, the following problem was found from gitlab CI pipeline:

> Responsibility.rst:: WARNING: unable to find image: /builds/build_confluence/plantuml-74f97ac86f0d8c2de9213012a36561a68e90e0b1.svg

However such svg files are actually generated properly when I browse these generated job artifacts. 
With such warning, rendered confluence HTML page ends up with a info note that shows the uml caption only.

What's going wrong and how to fix it?

BTW I have sphinx v4.5.0 installed + python 3.9, all extensions are installed by pip3.

**Comment by jdknight** [comment]
This is most likely an issue with this extension, failing to reference the image file interpreted from a node's `uri` field.

Some questions, if I may:

- Does configuring `plantuml_output_format = 'png'` yield different results? If it does not work with PNGs, we can ignore all the SVG-related implementation in this extension.
- For the `/builds/build_confluence/plantuml-*.svg` paths, is this folder/artifacts pathed at the root of the container (i.e. is the `/build` folder at the root)? Or are they nested in another folder (`/<some other path>/builds/...`)? Asking this since it has been seen in the past that a node may define an absolute-like path that is relative to the source directory; and some extensions creating images give a full absolute path.
- It is assumed this is a non-Windows container due to the path; however, if it is a Windows container, please let me know.

At this time, I suspect the issue is with the [`find_env_abspath`](https://github.com/sphinx-contrib/confluencebuilder/blob/98779f1619eed781301ecd089bc421963b2dd0a0/sphinxcontrib/confluencebuilder/util.py#L186) implementation.

**Comment by skyscribe** [comment]
Thanks @jdknight I'll try with png format and let you know if it works. To answer your questions:

For the /builds/ path, yes this is a Ubuntu based container and inside the container, absolute path is used.

**Comment by skyscribe** [comment]
I can also confirm this should be a regression since Sphinx v3.x + python 3.6 worked before. However I have to upgrade the toolchain to use new features from some builtin extensions.

**Comment by skyscribe** [comment]
@jdknight Actually after I applied below sed script:

`sed -i 's/\(plantuml_output_format=\).*/\1"png"/gp' conf.py`

Similar errors were reported like this:

> /builds/ohyJKKxT/0/<path_to_my_project>/Responsbility.rst:: WARNING: unable to find image: /builds/ohyJKKxT/0/<path_to_my_project>/build_confluence/plantuml-d9fb21f7213cd78c1443a636cd683466dfcc617f.png

**Comment by jdknight** [comment]
Tried some things today and was not able to reproduce this issue yet. Using a simple Docker container:

```
FROM archlinux

RUN pacman -Syu --noconfirm

RUN pacman -Sy \
    fontconfig \
    graphviz \
    plantuml \
    python-pip \
    ttf-dejavu \
    --noconfirm

RUN pip install \
    sphinxcontrib-confluencebuilder \
    sphinxcontrib-plantuml \
    -I
```

With a small PlantUML example:

```
plantuml
========

.. uml::

   Alice -> Bob: Hi!
   Alice <- Bob: How are you?
```

And running/publishing from the container appears to work. If you had any other recommendations on how I can tweak the container or invoke of Sphinx, I'd be happy to try it out and try to debug this situation more.

Also, additional modifications have been introduced in this extension to increase verbosity when processing images. If interested, you can install the [development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation), [enable verbosity](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-v) for the Sphinx call and see if it provides additional information on the image file path/processing.

**Comment by skyscribe** [comment]
I'd like to close this one after I upgrade my python version and docker image base. Could be some strange combo of python version + sphinx version + plugin version?

**Comment by nmosim** [comment]
I just stumbled upon the same issue. Images are generated by the plantuml extension, but never published as assets to Confluence.

Did you ever find what the issue was?
