### ISSUE TITLE
Request for new feature: provide override mode so stale children pages can be deleted automatically

### ISSUE THREAD

**Issue by skyscribe** [sphinx-contrib/confluencebuilder#674]
Currently it is a bit annoying when some files are just renamed or removed: when whole project is regenerated and exported to confluence (under a parent page), legacy pages would be retained by default so both new pages and old pages would be available. 

Not sure if there is any easy approach to perform smart merge, or cleanup everything before re-publishing new content.

Workaround exists though: 
1. If whole document is organized in good structure, one can delete the page hierarchy from Confluence UI
2. If pages are not organized in single root tree structure, one has to remove those pages one by one

**Comment by jdknight** [comment]
Have you tried using the [`confluence_purge`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_purge) option? Or is this a bit different to what you are looking for?

**Comment by skyscribe** [comment]
Would `confluence_purge` option not touch existing pages' comments if page title is kept as before?

**Comment by jdknight** [comment]
The `confluence_purge` option applies a basic process -- any pages of a _configured root_ will be deleted except for pages that were added or update. So yes, any comments that exist on a given page that has been updated, will remain on that page if `confluence_purge` is configured. Stale pages that `confluence_purge` detects will be removed; and in turn, will cause the comments for those pages to be removed as well (solely since the page does not exist). Page comments are never explicitly touched by this extension.

You can also try running with [`confluence_publish_dryrun`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confluence-publish-dryrun) to sanity check what would happen.

**Comment by skyscribe** [comment]
Thanks for helping out! 

It solves all of my problems.
