### ISSUE TITLE
Configuration via Environment Variables

### ISSUE THREAD

**Issue by tucked** [sphinx-contrib/confluencebuilder#679]
We have found ourselves frequently adding plumbing for plugin configs in `conf.py` e.g.
``` python
def getenvbool(*args: Any, **kwargs: Any) -> bool:
    """Read an environment variable as a boolean."""
    return os.getenv(*args, **kwargs).lower() in [
        "true",
        "1",
    ]


confluence_publish = getenvbool("confluence_publish", "false")
confluence_publish_dryrun = getenvbool("confluence_publish_dryrun", "false")
confluence_purge = getenvbool("confluence_purge", "false")

confluence_server_user = os.getenv("confluence_server_user")
confluence_server_pass = os.getenv("confluence_server_pass")
confluence_ask_user = confluence_server_user is None
confluence_ask_password = confluence_server_pass is None

...
```
After not working on the project for quite awhile, I returned to it and wanted to set `confluence_publish_postfix`, but I had forgotten about this plumbing. To get it to work, I had to add
```  python
confluence_publish_postfix = os.getenv("confluence_publish_postfix", "")
```
This got me thinking that it might just be handier to generalize this plumbing:
``` python
for key, value in os.environ.items():
    if key.startswith("confluence_"):
        if value.lower() in {"true", "false"}:
            value = bool(value)
        locals()[key] = value
```
However, that's not perfect since some configurations accept `int`s, `list`s, or `dict`s...

Would this project consider adding some help for this?
Perhaps it could accept any config via the environment or offer a function that reads config from the environment and returns it as a properly-typed dictionary e.g.
``` python
# no fancy type conversion needed!
locals().update(confluencebuilder_env_config())
```

**Comment by jdknight** [comment]
Typically in Sphinx environments, configuration overrides from outside `conf.py` are set [using the `-D` command line argument](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-D). However, I do not see a reason why we cannot make things even more convenient for users by supporting options from the environment as well.

To support something like this, I would imagine it would involve the following:
- Processing and assigning configuration options before the [configuration check](https://github.com/sphinx-contrib/confluencebuilder/blob/a7e2ffdb5d6e06a3e198a8353211cd629f2f014d/sphinxcontrib/confluencebuilder/builder.py#L94).
- It appears that Sphinx will [catch command line overrides](https://github.com/sphinx-doc/sphinx/blob/93226ca91acdba7fdf0c7efde27ccc9c28cf7ece/sphinx/config.py#L147) inside the configuration instance. It would be nice that command line overrides are selected with higher-priority over an environment variable-set configuration.
- We currently use some logic to processing string-types into configuration-specific desired types via the [`apply_defaults`](https://github.com/sphinx-contrib/confluencebuilder/blob/master/sphinxcontrib/confluencebuilder/config/defaults.py#L10) call. It maybe best to rework the implementation a bit so that the same type of string-to-target-type conversions are made.
- I would have no problem with argument parsing for complex types failing gracefully at first. For sure, options that accept types like `callable` types will never be supported. Sphinx's documentation indicates support for the `-D` arguments supporting list/dictionary types, which could be expanded on when introducing such an enhancement. But I would assume most users attempting to utilizing environment overrides were mainly target options of the string/integer/boolean variety.

I would feel a bit hesitant to apply any `confluence_` prefixed variable into the configuration instance. I would imagine it would be best to only apply options for valid options (and even complain about non-existent ones). There may be a way to check/track what options we register for this extension. Also, we have a least one option that is prefixed with `singleconfluence_`.

Another suggestion if we add support for environment options is that I would prefer to only accept environment options that are capitalized. For example, the `CONFLUENCE_PUBLISH` environment variable could be used to populate `confluence_publish`. Would that be OK for your use case?

**Comment by tucked** [comment]
Yes! That all makes sense and sounds workable 👍  I wasn't actually aware of `-D`! TIL...
However, `-D confluence_publish=0` seems to _enable_ publishing for me 🤔 (v1.8.0 + Sphinx 5.0.2)
For a little more context, we invoke `sphinx-build` via `tox.ini`:
``` ini
[tox]
minversion = 3.7.0
skipsdist = true
envlist = publish

[testenv]
basepython = python3.8
deps =
    myst-parser ~= 0.18.0
    sphinx ~= 5.0.0
    sphinxcontrib-confluencebuilder ~= 1.8.0

[testenv:publish]
commands =
    sphinx-build -b confluence docs {posargs:docs/_build/confluence}
```
``` sh
tox -e publish -- -D confluence_publish=0 docs/_build/confluence
```

**Comment by jdknight** [comment]
Changes introduced in #682 should provide some support for accepting configuration options from the command line. Precedence goes to Sphinx command line arguments, to a project's configuration file then to environment variables. Please let me know if that works for your use case.

**Comment by tucked** [comment]
>  All options provided by this extension may be set from the running
    environment. For example, if ``confluence_publish`` is not explicitly set
    inside ``conf.py`` or provided via `Sphinx's command line`_, this extension
    may check the ``CONFLUENCE_PUBLISH`` environment option as a fallback.

That's awesome! At this point we've set some defaults in `conf.py`  that we override with `-D`, but I could see this unlocking some interesting logic that wasn't possible before. For example, in `conf.py`, we could do
``` python
confluence_ask_user = "CONFLUENCE_SERVER_USER" not in os.environ
```
That wouldn't work without this AFAIK, because there's no way to tell something will be overridden with `-D` 😎
I'll have to play with it some more.

Thanks for being so responsive!
