### ISSUE TITLE
confluence_cleanup_archive hangs

### ISSUE THREAD

**Issue by marshall-mcmullen** [sphinx-contrib/confluencebuilder#713]
I am testing out the new feature added as part of https://github.com/sphinx-contrib/confluencebuilder/issues/697 that allows us to use the new experimental Confluence API to archive pages instead of deleting them and unfortunately it causes the publish job to hang indefinitely in my environment.

I've tried enabling `confluence_publish_debug` but it doesn't provide me any more information.

Interestingly, if I set `confluence_publish_dryrun = True`, it no longer hangs. It still displays the correct list of pages that _should_ be archived.

I know that this API is experimental but I'm just reporting this in case you have any ideas what might cause this, and also for visibility in case others encounter this behavior.

It is of course also possible this is just something specific to my environment. If others test this out please share your results. I'm going to try going back to `purge` instead of `archive` and see if it still hangs.

Thank you guys!

**Comment by marshall-mcmullen** [comment]
Well, it seems that this is hanging when I go back to `purge` instead of `archive` as well.

I even reverted to v1.8 and it is still hanging. This definitely sounds like something environmental. 

I'll keep digging and see if I can get to the bottom of it.

Thanks!

**Comment by marshall-mcmullen** [comment]
False alarm. This has nothing to do with `archive` which is great.

However, I am having a problem where periodically publishing an asset will hang indefinitely. The asset isn't even particularly large (100K). I'm going to continue debugging.

But for now this issue can be closed.

**Comment by jdknight** [comment]
@marshall-mcmullen, one thing you can try (if you haven't done already) is enabling the verbose flag (`-v`). For example:

```
python -m sphinx -b confluence . _build/confluence -E -a -v
```

The only thing I can imagine that could be delaying some events is due to the detection of rate-limiting from the remote server. While in some cases a warning message may be logged when this is detected, it is not guaranteed. If you enable verbosity, and you see "rate-limit header detected" messages, that is most likely the case (where this extension throttles API requests).

If it is the case that the instance you interact with is rate-limiting, it is hard to say what a step forward would be (there's not really much the extension can do). One may try to manually impose their own [`confluence_publish_delay`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_publish_delay) delay to see if manually delaying requests can prevent some sort of automatic throttling at a Confluence API access point may be imposing, but no guarantee that it would help (could even make things worse).

If you do not see any rate-limiting messages, I'm not sure what else it could be from this extension. You could try configuring [`confluence_timeout`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_timeout) for a more consistent failure approach if having issues interacting with the configured instance. The only other things that spawn off the top of my head is just how the Confluence instance (or reverse proxy to the instance) is configured. Depending on how many documents you may be trying to publish/process, there could be a chance a local firewall does not like all the API calls and drops requests -- but now we are really speculating.

**Comment by marshall-mcmullen** [comment]
Thank you so much for your detailed response @jdknight , it was helpful. After turning on the verbose flag, I saw that it was not hanging on the `purge` or the `archive` but on trying to upload one of the assets (an image). I ended up manually archive the page on confluence that contained the associated image, and the next time I published, everything worked, including archive!

I'll call this a fluke for now. if I see it again we can dig in further.

Thanks so much for your help

**Comment by marshall-mcmullen** [comment]
@jdknight 

In case anyone comes across this issue later, I ended up seeing this again in our environment. Only this time I was able to figure out that it was not caused by trying to upload an asset like I previously thought.

The hang happens for me 100% of the time in our environment.

What I ended up doing is enabling the configuration option `confluence_adv_aggressive_search = True`. When I enabled that setting, I was able to publish 100% of the time with no more hang!

I flipped the setting back to `confluence_adv_aggressive_search = False`, and re-ran it, and once again it would hang 100% of the time! I flipped it back to `True` and again the hang went away.

So there is definitely something about this setting which fixed this problem for me.
