### ISSUE TITLE
Implement SSO via browser authentication

### ISSUE THREAD

**Issue by v-au** [sphinx-contrib/confluencebuilder#728]
Related to #199, can a browser based login be implemented similarly to [AWS CLI SSO](https://github.com/aws/aws-cli/blob/v2/awscli/customizations/sso/utils.py) where upon authorization the cookie can be saved for future use?

**Comment by jdknight** [comment]
In theory, this should be possible for a user to setup. I do not have an environment to help sanity check, but from some online digging, it should be possible to do the following:

1) Install [AWS command line interface](https://aws.amazon.com/cli/). This should allow a user to authenticate with an AWS SSO using the `aws configure sso` command.
2) Install [Boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/quickstart.html). This is an AWS Python library package to help interact with AWS-related capabilities.
3) David Muller provides a [AWS Signature Version 4 Signing Process with Python Requests](https://github.com/DavidMuller/aws-requests-auth) package which, from README inspection only, should provide a way to easily use AWS SSO credentials and use in a Python Requests module (the module this Confluence extension uses for REST requests).

Once all three things are installed and a user have performed a sign-in using the AWS CLI, the following (inside `conf.py`) should be able to be used to configure authentication with this extension:

```
from aws_requests_auth.boto_utils import BotoAWSRequestsAuth

confluence_server_auth = BotoAWSRequestsAuth(
    aws_host='search-service-foobar.us-east-1.es.amazonaws.com',
    aws_region='us-east-1',
    aws_service='es')
```

Adjust the AWS options as needed for your environment.

----

Side note]
I want to clarify that this extension tries to be flexible in supporting various ways a user needs to manage various authentication types. If we want to improve this extension to better integrate with other libraries to improve various SSO implementation, the changes are welcome. However, we do not plan to add dependencies on this extension for optional features or features that cannot be gracefully tested. For example, AWS SSO will most likely utilize the boto3 library to manage authentication. This Sphinx extension will not add a boto3 dependency by default -- since not all users require AWS support, and development does not have a graceful way to test/validation these features. That being said, we are always willing to introduce configuration options and hooks, if needed, if it can help users interact with common or custom SSO solutions.

**Comment by v-au** [comment]
I brought up AWS CLI as a reference implementation, where we could grab the cookie from the browser post login rather than hardcoding it, an approach that I thought would work irrespective of the SSO provider (in fact I authenticate via O365).  I'll see if, with my limited Python experience, I can hack something.

Thanks for this great extension.
________________________________

**Comment by jdknight** [comment]
I will be going ahead and closing this issue.

While this extension tries to improve the user experience when interacting with a Confluence instance, to support various SSOs is a complex world. How an individual Confluence instance is configured with an SSO layer in enterprise environments varies, depending on what SSO provider is used (not including custom SSO implementations). Due to the vast number of configurations possible, there will most likely be no specific SSO-related integration added into this repository.

This extension currently provide various ways to users to tailor authentication capabilities with even direct access to Request sessions, injecting header fields, etc.; and users with unique SSO environments should be able to tailor their configurations to support browser-based authentication (assuming the third-party SSO solution provides support to do so).

Users which may be attempting to publish to a Confluence instance which is enforced with a custom SSO are recommended to discuss requirements for authentication with the DT/IT contacts. Users are welcome to make suggestions towards this extension's publication configuration if there is a possible limitation when interacting with a certain Confluence environment.
