### ISSUE TITLE
server did not provide an expected response (no size)

### ISSUE THREAD

**Issue by mowen0107** [sphinx-contrib/confluencebuilder#732]
Hi everyone. I'm trying to publish some docs on my company's confluence. However, this problem stumped me.

I read the source code(master branch), and found the REST API "GET /api/space" in **ConfluencePublisher.connect** is little bit different from the API I use. This caused it to keep reporting the error "server did not provide an expected response (no size)" when I run "make confluence".

In detail, in ConfluencePublisher.connect method, the "spaceKey" field is placed in the params dict, and the final request will be "/api/space?spaceKey=keyabc". But the Confluence Official Documation shows that the value of "spaceKey" is part of the URL path, and the final request will be "/api/space/keyabc".

The usage in ConfluencePublisher.connect method:
https://github.com/sphinx-contrib/confluencebuilder/blob/9d7d5bfad41a5d89a26960f3a07f7e416a9b175a/sphinxcontrib/confluencebuilder/publisher.py#L63-L78

The usage in Confluence Official Documation example:
![image](https://user-images.githubusercontent.com/10389041/200305550-c3d4f1ef-2e47-4df6-8007-a41dcd3ab6ad.png)

So why is there such a difference? Is it because the API versions on both sides are different, or some other reasons?
Please correct me if I have any wrong understanding of the source code or package usage here. Thanks.

Platform: Windows
Python version: 3.9.2
Package version: 1.9.0

The Confluence Official Documation link:
https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-space/#api-wiki-rest-api-space-spacekey-get

**Comment by jdknight** [comment]
This extension uses the ["Get Spaces"](https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-space/) API call over the mentioned "Get Space" API call when attempting to find the target space information. The main reason for this was to help distinguish the error case between either the space does not exist/or no permissions to access it (size==0); over the case where the host is not a Confluence instance (errno 404).

To get a `server did not provide an expected response (no size)` message gives me the impression that the Confluence instance being connected to either formed a bad response (since it is missing the `size`) value, another instance (e.g. proxy) is somehow reporting a JSON-like response, or there is a bug/use case not handled in this extension's implementation.

**Comment by mowen0107** [comment]
> This extension uses the ["Get Spaces"](https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-space/) API call over the mentioned "Get Space" API call when attempting to find the target space information. The main reason for this was to help distinguish the error case between either the space does not exist/or no permissions to access it (size==0); over the case where the host is not a Confluence instance (errno 404).
> 
> To get a `server did not provide an expected response (no size)` message gives me the impression that the Confluence instance being connected to either formed a bad response (since it is missing the `size`) value, another instance (e.g. proxy) is somehow reporting a JSON-like response, or there is a bug/use case not handled in this extension's implementation.

Thanks a lot! Now I know where I went wrong. I should have read the official documentation more carefully.

I read my company's api documentation again and found the "Get Spaces" api call is not supported. Maybe it's because I don't have high-level permissions. So I have to find another way/extension to solve this problem. T_T

Thanks again~
