### ISSUE TITLE
nbsphinx and ipython

### ISSUE THREAD

**Issue by finkedave** [sphinx-contrib/confluencebuilder#764]
Until a month ago we were using our own hacked together sphinx confluence builder extension to publish jupyter notebooks to confluence. We saw that it is natively supported now within this repository in 2.0 so we tried it out, looks like it was able to write the output for our jupyter notebooks but we are getting two warnings now after it writes them. 

```
preparing documents... done
writing output... [ 25%] docking_pipeline/P3DOCK_requests
writing output... [ 33%] docking_pipeline/RNAComposer_requests
...
WARNING: unsupported code language for confluence: ipython3

WARNING: unsupported code language for confluence: ipython2
```
(Neither of these are being used within our jupyter notebooks, as far as I know)

Not sure if we are missing something with compatibility with this new feature and our notebooks, any advice would be greatly appreciated.

As a side note. I do see that ipython is not supported in confluence builder editor v1 or v2, so can't this new extension just use python as the code block instead?

**Comment by jdknight** [comment]
Unknown off hand what specific directives used will result a final doctree with `ipython2` and `ipython3` styled code blocks. I would imagine any directive type which would expect to produce an IPython-like block would be the "offending" directive.

While the Confluence builder extension does provide improved support for this third-party extension, I would believe it is still proper that unregistered code types like `ipython2` and `ipython3` should still generate warnings (since Confluence cannot properly render an interactive Python block). That being said, you do make a good point that for a case such as this, it may be ideal to fallback the "unsupported" Python-like code style to Python (instead of the default `none`). We may also want to add a generic configuration flag to operate styling in a relaxed/suppressed mode, for users who understand syntax limitations with Confluence, and are fine with whatever appropriate style is used.

For now, you could use the [`confluence_lang_transform`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_lang_transform) configuration and add the following in your documentation's configuration to convert the IPython styles to a `python` style:

```
def translation_override(lang):
    if lang in ['ipython', 'ipython2', 'ipython3']:
        lang = 'python'

    return lang

confluence_lang_transform = translation_override
```

**Comment by finkedave** [comment]
Thanks, that did the trick. didn't realize that transform override existed till now. Super good to know. Wasn't sure if i should close this ticket or leave it open for the Python fallback piece but feel free to close this issue if you would prefer to have that as a separate ticket.

**Comment by jdknight** [comment]
We can leave this open to as a reference to cleanup the code language types.

A quick overview of the planned changes:
- Create an additional code-style dictionary for extra fallback styles -- at the minimum, supporting interactive Python code stylings to fallback to Python code stylings.
- When `confluence_lang_transform` is used, allow the call to support returning a `None` value to indicate to use the default color mapping.
- Investigate the use of Sphinx's [`suppress_warnings`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-suppress_warnings) configuration to suppress unknown code language (and maybe other) warnings (if not already supported).

**Comment by jdknight** [comment]
Adjustments outlined in #769 and #770 have been merged into the development tree. These two pull requests cover the above enhancement points made in the previous comment. For users wishing to take advantage of these changes before a release is made, the [development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation) of this extension can be installed.

The following shows an example of suppressing code warnings for projects who may not care about unsupported or non-direct language types:

```
suppress_warnings = [
    'confluence.unsupported_code_lang',
]
```

**Comment by jdknight** [comment]
v2.1 is now available on PyPI -- marking as closed.
