### ISSUE TITLE
Problem with `confluence_full_width` setting/Better Sphinx-Needs Integration

### ISSUE THREAD

**Issue by mason3k** [sphinx-contrib/confluencebuilder#794]
When I use Confluence Builder with sphinx-needs (see https://sphinx-needs.readthedocs.io/), the formatting is odd (horizontal scrollbar for no content) and it appears that the `confluence_full_width` setting is not respected.

![image](https://user-images.githubusercontent.com/48703453/233698609-1eb97c28-a5aa-4675-87c7-7b7b5aeefb83.png)

This is generated with ``confluence_full_width` set to `False`

It's especially strange because in edit mode, it looks like this element is just being rendered as a table cell. I would expect a table to respect the full_width setting.
![image](https://user-images.githubusercontent.com/48703453/233698879-7a810f39-7001-47e5-952b-158fdb052906.png)

**Comment by jdknight** [comment]
Thanks for reporting this. While the Confluence builder does not have in-depth support for all the various layout types sphinx-needs provides, there are some rendering quirks observed (from OP and some additional testing) that are not expected when using the v2 editor (doubt any third-party extension was really tested with the initial release of v2 editor support).

Prepared a pull request (https://github.com/sphinx-contrib/confluencebuilder/pull/795) which should help improve things. The biggest one would be the inconsistencies with the `confluence_full_width` option (when configured to default/`False`). When adding Sphinx-needs support for the v1 editor, tables were configured to 100% to mimic what was observed in the HTML builder. And looks like in the v2 editor, anything styled with 100% width can break the page's width formatting option. The changes should address this by not applying 100% widths when using the v2 editor (since Confluence's v2 editor will 100% tables automatically in a way that won't break a page's width option).

If you are interested in trying this out ahead of time, the following command can be used:

```
pip install git+https://github.com/sphinx-contrib/confluencebuilder.git@improve-sphinx-needs-interaction
```

Additional tweaks have also been introduced to improve rendering. Although note that it will won't be perfect. There are some limitations in what Confluence can do in a way to "match" the styling observed when using the HTML builder. If you do try it out and notice a way to improve a certain use case (i.e. if you tweak an output style in a way to render in a possibly nicer way), it is recommended to include an example before/after capture of the pages (and raw source content can help as well).

**Comment by mason3k** [comment]
Thank you, that resolved my problem!

**Comment by jdknight** [comment]
v2.1 is now available on PyPI -- marking as closed.
