### ISSUE TITLE
Skip docs without modifications

### ISSUE THREAD

**Issue by pe1uca** [sphinx-contrib/confluencebuilder#799]
Could there be a way to prevent the builder from publishing a page that hasn't been modified?  

The issue comes when trying to notify users of updates. I see [confluence_disable_notifications](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_disable_notifications) exists, but this will disable notifications for all pages and you need to manually change it.  

---  

Here's an example, using this tree:  
![image](https://user-images.githubusercontent.com/15692727/234376917-6a0566a3-d95f-4d6c-87d0-b0c40a6588cd.png)

Users would be interested to watch "Changelog".  
Currently if we forget to set the flag when updating the other pages users would get a notification even when nothing new was included in the changelog.  
Even if we don't forget this also has the drawback of picking only between notifying about all pages or non at all.  
We aren't able to update "Overview" and just notify users watching that page without also sending a notification to "Changelog".  

With a test it was also confirmed if the user has "Watch all content in this space" will receive a separate notification by each page in the docs.  

---  

During the publish the page is already retrieved to get the version, maybe the content could also be retrieved to compare with what is being to be published and if they're the same skip publishing it.  

https://github.com/sphinx-contrib/confluencebuilder/blob/5e9e0384cdef148d8d20b95ff2d5d2bc27c9d33c/sphinxcontrib/confluencebuilder/publisher.py#L765-L769

**Comment by pe1uca** [comment]
Found a workaround using [confluence_publish_allowlist](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_publish_allowlist) along with git.  

Retrieve the files changed in the branch being merged (it could also be done with commit's SHA).  
Use grep to only retrieve files inside the docs folder and also remove the config file (it could be changed to `grep '.rst'` if there are other kind of files in the docs folder).  
Use sed to format the name as needed by [the validator](https://github.com/sphinx-contrib/confluencebuilder/blob/5e9e0384cdef148d8d20b95ff2d5d2bc27c9d33c/sphinxcontrib/confluencebuilder/config/validation.py#L163)  
```bash
$ git fetch origin
$ export FILES_CHANGED=$(git diff --name-only --no-commit-id origin/source_branch origin/target_branch | grep '^docs/source/' | grep -v '.py' | sed -e 's/^docs\/source\///g' -e 's/\.[^.]*$//')
$ sphinx-build -b confluence -t confluence docs/source/ docs/build/confluence -E -a
```

In `conf.py` we retrieve the variable, it's a string with the file names separated by lines, so we use `split()` to retrieve a list as needed by the builder.  
```py
confluence_publish_allowlist = os.getenv('FILES_CHANGED').split()
```

**Comment by jdknight** [comment]
It should be possible to support something like this.

I believe the original intention of the allow/deny list was to somewhat support this capability. Developers can use their tools to detect changes in sources, an configure these lists on the fly to only publish changed documentation (as your example has shown; thanks for sharing, it's good to know how people achieve these scenarios which could help others). Granted, preparing an environment for this is not always trivial.

One thing to consider is the version of a page may not be a good indication to tracking "what has changed" from the context of a Sphinx publisher. Mainly since there is no guarantee that an environment knows what the last version published (for cases where publishing is handled in containers, or having different users publishing from their respective development environments).

We could mimic a style like we do with our attachments. At this time, when we generate an attachment for a page, the comment field will be assigned a hash of the uploaded file. And when we re-publish, we only re-upload an attachment if the detected hash changes. While it could be nice to use the version update message for such hash-tracking for a page, (1) users can already tailor their version comments so their liking (so we may not want to touch it), and (2) Confluence server does not support assigning a version text on the first page update.

Looking at Confluence's API, there is something called ["Confluence entity properties"](https://developer.atlassian.com/cloud/confluence/confluence-entity-properties/#content-properties), which could help. I've only stumbled upon it recently, but maybe we can track a hash value in a page's properly and reference it if we need to do a page update (assuming this works for both Confluence Cloud and Server/DC).

Lastly, a more simpler approach (but possibly more costly) is that we could take advantage of the existing `get_page` call referenced above. At this time, the `get_page` will not fetch the existing contents of the page (just metadata); however, we could tweak it to always fetch the content as well, and generate a hash to compare if something is changed before publishing.

**Comment by jdknight** [comment]
Adjustments have been applied via https://github.com/sphinx-contrib/confluencebuilder/pull/801 and merged into the development tree which should improve support for limiting page updates if content has not changed. For users interested in trying this capability before a release is made, the [development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation) of this extension can be installed.

**Comment by jdknight** [comment]
v2.1 is now available on PyPI -- marking as closed.
