### ISSUE TITLE
Support for .. raw:: html type

### ISSUE THREAD

**Issue by EleniSmyrniou** [sphinx-contrib/confluencebuilder#821]
This is more of a feature request. It would be nice if we can include embeded html files in confluence via this package. That enables people to intergrate plotly plots in their documentation.

**Comment by jdknight** [comment]
Note that this extension has an undocumented configuration which will permit the use of raw HTML content to be published to a Confluence instance:

```
confluence_adv_permit_raw_html = True
```

Note that this option is not supported and may have undesired effects when attempting to publish such as:

- Confluence may abort/fail the publish request
- When viewing the page with HTML content, content may be missing or may not render as expected

This extension does not support a means of translating HTML content into compatible Confluence’s storage format due to the limitations of the format (when compared to HTML) and restrictions on Confluence (due to Confluence's security module).

**Comment by jdknight** [comment]
Adjustments have been applied via #824 and merged into the development tree which now introduces support for a `confluence_permit_raw_html` configuration option. **This is still considered an unsupported option** but will be publicly documented, allow users to opt-in to its capabilities if they so desire. This configuration operates just as the undocumented `confluence_adv_permit_raw_html` option did; however, it now also supports being configured with a string-value to allow users alternatively to use an HTML-macro instead (if available on the Confluence instance they are publishing to).

This configuration will be available in the next release (v2.2+). For users wanting this capability before a release is made, the [development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation) of this extension can be installed.

**Comment by jdknight** [comment]
v2.2 is now available on PyPI -- marking as closed.
