### ISSUE TITLE
Support confluent sidebar hierarchy

### ISSUE THREAD

**Issue by AVMusorin** [sphinx-contrib/confluencebuilder#852]
I cannot publish pages with the same hierarchy as they are stored on the file system. In the confluence sidebar all pages are located after root page (no hierarchy at all).
```
(system)
 platform: Linux-6.5.8-arch1-1-x86_64-with-glibc2.38
   python: 3.10.11 (main, Jul 24 2023, 18:40:22) [GCC 13.1.1 20230429]
   sphinx: 5.3.0
 docutils: 0.19
 requests: 2.31.0
  builder: 2.0.0

(configuration)
confluence_cleanup_from_root: True
confluence_cleanup_purge: True
confluence_disable_ssl_validation: True
confluence_page_hierarchy: True
confluence_publish: True
confluence_publish_debug: False
confluence_publish_dryrun: False
confluence_publish_root: (set)
confluence_server_url: https://<removed>
confluence_space_key: (set; upper)

(confluence instance)
 connected: no
```

Inside index.md I added a content with all my folders like:

```
# Documentation

{toctree}
folder1
folder2
home
```

It works fine to generate content table, but sidebar is still flat.

**Comment by jdknight** [comment]
Last I recall, Confluence does not yet provide an API to configure the order of entries on the sidebar.

I believe by default, pages are sorted by A-Z, but pages can be resorted manually by users after a publish attempt in Confluence's UI. Furthermore, future publish updates will not change any existing ordering on a page. Although, this does not help users who expect to publish new pages/subsets at a high frequency.

If Atlassian provides support for sorting via APIs in the future, I would agree that this extension should be using such a feature/capability by default to match the order expected in other Sphinx builders. And if such APIs do exist and I have overlooked them, please let me know.

**Comment by AVMusorin** [comment]
Thank you. I'll try to reorder them by myself. 

By the way, what do you think is it possible to get around this limitation and push requests with a parent page for every child according to their hierarchy?

**Comment by jdknight** [comment]
I'm not sure how much that workaround could work. For sure one could try to tailor specific parent pages for each child, but the parent pages themselves would still be "default sorted" (unless I have misunderstood the suggested workaround).

I do recall looking at some of the REST API response and seeing some page extension hints which may have hinted at page ordering. If I have a change to dive into that logic sometime in the future, I'll try to see what those extension entries are for ~ although, it could be nothing.

**Comment by AVMusorin** [comment]
I can try to help you if you a little bit help me at the start and give me some clues, for example, I tried to debug the library but did not find how to request confluence API (since I created the PR, to check how it will be published).

**Comment by jdknight** [comment]
If we look at the [published validation example](https://sphinxcontrib-confluencebuilder.atlassian.net/wiki/spaces/STABLE/pages/502039901), these pages are published each release and manual tweaks are made to sort the left side ~ where we first promote reStructredText, Sphinx-specific, etc.:

![image](https://github.com/sphinx-contrib/confluencebuilder/assets/1834509/79d3c505-ec6b-4ba0-ad6c-4c47ced33628)

When looking at the content for the "Default editor" and it's children using [Confluence's "Get content by ID" call](https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-content/#api-wiki-rest-api-content-id-get), there looks to be an undocumented entry `extensions` for each page. And under the extensions list, there is a `position` type with a numeric value. There is an assumption that this is the value used to help sort pages, but an investigation on this was never performed.

```
{
  "id": "502137655",
  "type": "page",
  "title": "Sphinx",
  ...
  "extensions": {
    "position": 269307213
  },
  ...
}
```

You can try to tweak this extension's [publisher](https://github.com/sphinx-contrib/confluencebuilder/blob/main/sphinxcontrib/confluencebuilder/publisher.py) to apply this value, see if the order can be manipulated. If so, try to possibly build a incremental bump of position publishing pages. No idea the best approach on dealing with more complex scenarios such as dealing with re-updates, dealing with new pages added which adjust ordering, etc.

And a side note, it looks like Confluence's v2 REST API (which this extension will need to eventually shift to), does not look to accept additional properties provided in page calls (e.g. [v1](https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-content/#api-wiki-rest-api-content-id-put) vs [v2](https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-page/#api-pages-id-put)) (although, it could be undocumented since it is not supported).

**Comment by AVMusorin** [comment]
I found out that it can work out of the box, and we just need to create the right `toctree` in every subdirectory.

For example, let's assume we have the following hierarchy:

```
├── folder
│   └── folder.rst
│   └── text.rst
├── index.rst
└── table.rst
```

`index.rst` should have the following content:

```rst
.. toctree::
   folder/folder.rst
   table.rst
```

And `folder/folder.rst` :

```rst
.. toctree::
   text.rst
```

I have to generate it manually, but I guess it's nice to have this kind of feature to generate these toctree automatically with `:hidden` flag.

**Comment by jdknight** [comment]
I will be marking this issue as closed, as there appears to be a way to structure documentation as desired with the existing implementation with a change noted in this issue.

There was mention of possible ways to hint to Confluence specific sort order for pages, but since the v2 API does not appear to support this, there is no plan to dive into that approach as well. With this in mind, I have applied a wontfix tag. Feel free to re-open this issue or create a new one if such a capability does become available in Confluence's APIs.
