### ISSUE TITLE
Jira role handling in non-Confluence builders

### ISSUE THREAD

**Issue by tucked** [sphinx-contrib/confluencebuilder#868]
Is there a way to render a plain link to Jira when using the `html` builder on a project with a Jira role?

**Comment by jdknight** [comment]
The stock implementation of this extension does not support a way to include the Jira role (let alone other custom roles/directives introduced by this extension) in any builder other than the `confluence` or `singleconfluence` builders. There is also no immediate plans to support these in the `html` (or other builders), since most (if not all) do not apply (e.g. `confluence_metadata`), multiple builder support is provided by another extension (e.g. instead of using `confluence_expand`, use sphinx-toolbox's `collapse` directive), or configurations set do not apply to other builds (e.g. `jira` directive/roles with no graceful way to map to a Jira instance since it relies on either Confluence or UUID values).

However, there are some custom tweaks are user can do for their documentation to crudely utilize this extension's Jira role to provide a simple link in `html` builders. For example, consider the following `conf.py` implementation:

```
from docutils import nodes
from sphinxcontrib.confluencebuilder.builder import ConfluenceBuilder
from sphinxcontrib.confluencebuilder.nodes import jira_issue
from sphinxcontrib.confluencebuilder.roles import JiraRole


extensions = [
    'sphinxcontrib.confluencebuilder',
]


jira_base_url = 'https://example.atlassian.net/browse/'


def custom_visit_jira_issue(self, node):
    key = node.params['key']
    self.body.append(f'<a href="{jira_base_url}{key}">{key}</a>')
    raise nodes.SkipNode


def setup(app):
    app.connect('builder-inited', builder_inited)


def builder_inited(app):
    # register Jira role support for builders when not running a
    # Confluence builder extension builder
    if not isinstance(app.builder, ConfluenceBuilder):
        app.add_node(jira_issue,
            html=(custom_visit_jira_issue, None),
            override=True)
        app.add_role('jira', JiraRole)
```

The above will inject support for this extension's `jira` role when using the `html` builder. And when a `jira` role is processed, it will generate a simple HTML link to a Jira key using the configure Jira base URL.
